from __future__ import annotations

import argparse
from datetime import date, timedelta
from pathlib import Path

import pandas as pd


DEFAULT_RUN_DATE = date.today()
CALENDAR_COLUMNS = [
    "event_type",
    "venue_key",
    "venue",
    "date",
    "days_until_date",
    "urgency",
    "title",
    "description",
    "source_item",
    "source_status",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build CSV, Markdown, and ICS calendar reminders from the submission critical path."
    )
    parser.add_argument(
        "--critical-path",
        default="reports/assets/submission_critical_path.csv",
        help="Machine-readable critical path generated by build_submission_critical_path.py.",
    )
    parser.add_argument(
        "--out-path",
        default="reports/submission_deadline_calendar_2026_06_15.md",
        help="Markdown calendar summary to write.",
    )
    parser.add_argument(
        "--csv-out",
        default="reports/assets/submission_deadline_calendar.csv",
        help="Machine-readable calendar event list to write.",
    )
    parser.add_argument(
        "--ics-out",
        default="reports/assets/submission_deadline_calendar.ics",
        help="iCalendar file with all-day milestone/deadline events.",
    )
    parser.add_argument(
        "--run-date",
        default=DEFAULT_RUN_DATE.isoformat(),
        help="Date used for countdowns, in YYYY-MM-DD format. Defaults to today's local date.",
    )
    return parser.parse_args()


def _markdown_escape(value: object) -> str:
    if value is None or pd.isna(value):
        return ""
    return str(value).replace("\n", " ").replace("|", "\\|")


def _markdown_table(frame: pd.DataFrame, columns: list[str]) -> str:
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame[columns].itertuples(index=False):
        lines.append("| " + " | ".join(_markdown_escape(value) for value in row) + " |")
    return "\n".join(lines)


def _urgency(days_until_date: int) -> str:
    if days_until_date < 0:
        return "overdue"
    if days_until_date <= 3:
        return "due_now"
    if days_until_date <= 7:
        return "due_this_week"
    if days_until_date <= 14:
        return "due_next_two_weeks"
    return "scheduled"


def _ics_escape(value: object) -> str:
    text = "" if value is None or pd.isna(value) else str(value)
    return (
        text.replace("\\", "\\\\")
        .replace(";", "\\;")
        .replace(",", "\\,")
        .replace("\r\n", "\\n")
        .replace("\n", "\\n")
    )


def _ics_date(value: str) -> str:
    return date.fromisoformat(value).strftime("%Y%m%d")


def _fold_ics_line(line: str) -> list[str]:
    if len(line) <= 75:
        return [line]
    folded = []
    current = line
    while len(current) > 75:
        folded.append(current[:75])
        current = " " + current[75:]
    folded.append(current)
    return folded


def _venue_deadline_rows(critical_path: pd.DataFrame, run_date: date) -> list[dict[str, object]]:
    rows = []
    for venue_key, group in critical_path.groupby("venue_key", sort=False):
        first = group.iloc[0]
        deadline = date.fromisoformat(str(first["deadline"]))
        rows.append(
            {
                "event_type": "venue_deadline",
                "venue_key": venue_key,
                "venue": first["venue"],
                "date": deadline.isoformat(),
                "days_until_date": (deadline - run_date).days,
                "urgency": _urgency((deadline - run_date).days),
                "title": f"{venue_key} final submission deadline",
                "description": f"Final deadline for {first['venue']}. Packet status: {first['packet_status']}.",
                "source_item": "venue deadline",
                "source_status": first["packet_status"],
            }
        )
    return rows


def _target_rows(critical_path: pd.DataFrame) -> list[dict[str, object]]:
    rows = []
    for item in critical_path.itertuples(index=False):
        rows.append(
            {
                "event_type": "target_done_by",
                "venue_key": item.venue_key,
                "venue": item.venue,
                "date": item.target_done_by,
                "days_until_date": item.days_until_target,
                "urgency": item.urgency,
                "title": f"{item.venue_key} target: {item.item}",
                "description": item.action,
                "source_item": item.item,
                "source_status": item.status,
            }
        )
    return rows


def _write_ics(events: pd.DataFrame, ics_path: Path, run_date: date) -> None:
    lines = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        "PRODID:-//SCP-Fusion//Submission Deadline Calendar//EN",
        "CALSCALE:GREGORIAN",
        "METHOD:PUBLISH",
        f"X-WR-CALNAME:SCP-Fusion Submissions {run_date.year}",
    ]
    stamp = run_date.strftime("%Y%m%d")
    for event in events.itertuples(index=False):
        start = date.fromisoformat(str(event.date))
        end = start + timedelta(days=1)
        uid = f"{event.venue_key}-{event.event_type}-{start.strftime('%Y%m%d')}-{event.source_item}".lower()
        uid = "".join(character if character.isalnum() else "-" for character in uid).strip("-")
        lines.extend(
            [
                "BEGIN:VEVENT",
                f"UID:{uid}@scp-fusion.local",
                f"DTSTAMP:{stamp}T000000Z",
                f"DTSTART;VALUE=DATE:{_ics_date(str(event.date))}",
                f"DTEND;VALUE=DATE:{end.strftime('%Y%m%d')}",
                f"SUMMARY:{_ics_escape(event.title)}",
                f"DESCRIPTION:{_ics_escape(event.description)}",
                f"CATEGORIES:{_ics_escape(event.venue_key)},{_ics_escape(event.event_type)},{_ics_escape(event.urgency)}",
                "TRANSP:TRANSPARENT",
                "END:VEVENT",
            ]
        )
    lines.append("END:VCALENDAR")
    folded = [folded for line in lines for folded in _fold_ics_line(line)]
    ics_path.parent.mkdir(parents=True, exist_ok=True)
    ics_path.write_text("\n".join(folded) + "\n", encoding="utf-8", newline="\r\n")


def build_deadline_calendar(
    critical_path_path: Path,
    out_path: Path,
    csv_out: Path,
    ics_out: Path,
    run_date: date = DEFAULT_RUN_DATE,
) -> tuple[str, pd.DataFrame]:
    critical_path = pd.read_csv(critical_path_path)
    rows = _target_rows(critical_path) + _venue_deadline_rows(critical_path, run_date)
    events = pd.DataFrame(rows, columns=CALENDAR_COLUMNS).sort_values(
        ["date", "event_type", "venue_key", "source_item"],
        ignore_index=True,
    )
    csv_out.parent.mkdir(parents=True, exist_ok=True)
    events.to_csv(csv_out, index=False)
    _write_ics(events, ics_out, run_date)

    by_type = (
        events.groupby(["event_type", "urgency"], sort=False)
        .size()
        .reset_index(name="events")
    )
    preview = events[
        [
            "date",
            "days_until_date",
            "urgency",
            "event_type",
            "venue_key",
            "title",
        ]
    ]
    lines = [
        "# Submission Deadline Calendar",
        "",
        f"Run date: {run_date.isoformat()}",
        "",
        "Generated by `scripts/build_submission_deadline_calendar.py` from the submission critical path.",
        "",
        "This report turns the remaining writing/export queue into importable all-day calendar events. It does not change benchmark claims or venue readiness status.",
        "",
        "## Event Summary",
        "",
        _markdown_table(by_type, list(by_type.columns)),
        "",
        "## Calendar Events",
        "",
        _markdown_table(preview, list(preview.columns)),
        "",
        f"Machine-readable events: `{csv_out.as_posix()}`",
        "",
        f"Importable calendar: `{ics_out.as_posix()}`",
        "",
    ]
    text = "\n".join(lines)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    return text, events


def main() -> None:
    args = parse_args()
    text, _events = build_deadline_calendar(
        critical_path_path=Path(args.critical_path),
        out_path=Path(args.out_path),
        csv_out=Path(args.csv_out),
        ics_out=Path(args.ics_out),
        run_date=date.fromisoformat(args.run_date),
    )
    print(Path(args.out_path).resolve())
    print(Path(args.csv_out).resolve())
    print(Path(args.ics_out).resolve())
    if not text:
        raise SystemExit("No deadline calendar report generated")


if __name__ == "__main__":
    main()
