from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from forensic_compare.conventional import feature_names


RUN_DATE = "2026-06-14"

DESCRIPTIONS = {
    "recon_half_abs_mean": "Mean RGB residual after bicubic downsample-to-half and upsample reconstruction.",
    "recon_half_abs_p95": "95th percentile RGB residual after half-scale reconstruction.",
    "recon_half_luma_chroma_ratio": "Ratio of luma reconstruction residual to chroma reconstruction residual at half scale.",
    "recon_half_laplacian_abs_mean": "Mean absolute Laplacian of the half-scale reconstruction residual map.",
    "recon_half_tile16_std_mean": "Mean local residual standard deviation over 16x16 tiles at half scale.",
    "recon_half_tile16_std_p90": "90th percentile local residual standard deviation over 16x16 tiles at half scale.",
    "recon_quarter_abs_mean": "Mean RGB residual after bicubic downsample-to-quarter and upsample reconstruction.",
    "recon_quarter_abs_p95": "95th percentile RGB residual after quarter-scale reconstruction.",
    "recon_quarter_luma_chroma_ratio": "Ratio of luma reconstruction residual to chroma reconstruction residual at quarter scale.",
    "recon_quarter_laplacian_abs_mean": "Mean absolute Laplacian of the quarter-scale reconstruction residual map.",
    "recon_half_quarter_abs_mean_delta": "Half-minus-quarter delta for mean reconstruction residual.",
    "recon_half_quarter_abs_p95_delta": "Half-minus-quarter delta for 95th percentile reconstruction residual.",
    "recon_half_quarter_luma_chroma_ratio_delta": "Half-minus-quarter delta for luma/chroma reconstruction residual ratio.",
    "recon_half_quarter_laplacian_delta": "Half-minus-quarter delta for residual Laplacian energy.",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Document the standalone reconstruction_lite feature family."
    )
    parser.add_argument(
        "--out-path",
        default="reports/reconstruction_lite_feature_set_2026_06_14.md",
        help="Markdown report to write.",
    )
    parser.add_argument(
        "--csv-out",
        default="reports/assets/reconstruction_lite_feature_manifest.csv",
        help="Machine-readable feature manifest to write.",
    )
    return parser.parse_args()


def _family(name: str) -> str:
    if name.startswith("recon_half_quarter"):
        return "cross_scale_delta"
    if name.startswith("recon_half"):
        return "half_scale_resize_residual"
    if name.startswith("recon_quarter"):
        return "quarter_scale_resize_residual"
    raise ValueError(f"Unexpected reconstruction feature name: {name}")


def build_manifest() -> pd.DataFrame:
    rows = []
    for index, name in enumerate(feature_names("reconstruction_lite"), start=1):
        rows.append(
            {
                "order": index,
                "feature_name": name,
                "family": _family(name),
                "description": DESCRIPTIONS[name],
                "status": "implemented_standalone_ablation",
            }
        )
    return pd.DataFrame(rows)


def _markdown_escape(value: object) -> str:
    if value is None or pd.isna(value):
        return ""
    return str(value).replace("\n", " ").replace("|", "\\|")


def _markdown_table(frame: pd.DataFrame, columns: list[str]) -> str:
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame[columns].itertuples(index=False):
        lines.append("| " + " | ".join(_markdown_escape(value) for value in row) + " |")
    return "\n".join(lines)


def write_report(manifest: pd.DataFrame, out_path: Path, csv_out: Path) -> None:
    family_counts = manifest.groupby("family", sort=False).size().reset_index(name="feature_count")
    lines = [
        "# reconstruction_lite Feature Set",
        "",
        f"Run date: {RUN_DATE}",
        "",
        "Generated by `scripts/build_reconstruction_lite_feature_report.py` from `forensic_compare.conventional.feature_names(\"reconstruction_lite\")`.",
        "",
        "`reconstruction_lite` is a standalone AEROBLADE-lite style ablation for the current single-image benchmark setup. It does not run a learned diffusion or autoencoder reconstructor; instead, it measures deterministic bicubic downsample/upsample residuals at half and quarter scale, then adds cross-scale deltas. That keeps the branch fast, deterministic, and separable from `combined_v4`.",
        "",
        "## How To Run",
        "",
        "```powershell",
        "python scripts/run_feature_baseline.py `",
        "  --data-dir data/raw/ishu-2024-ai-generated-vs-real-images/dataset `",
        "  --output-dir runs/reconstruction_lite_probe/seed7 `",
        "  --feature-set reconstruction_lite `",
        "  --classifier logistic_regression `",
        "  --seed 7",
        "```",
        "",
        "For a physics-guided neural ablation, pass `--physics-feature-set reconstruction_lite` to `scripts/train_physics_guided_net.py`. The existing `combined_v3` and `combined_v4` definitions are unchanged, so old metrics remain comparable.",
        "",
        "## Feature Families",
        "",
        _markdown_table(family_counts, ["family", "feature_count"]),
        "",
        "## Manifest",
        "",
        _markdown_table(manifest, ["order", "feature_name", "family", "description", "status"]),
        "",
        f"Machine-readable manifest: `{csv_out.as_posix()}`",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    manifest = build_manifest()
    csv_out = Path(args.csv_out)
    csv_out.parent.mkdir(parents=True, exist_ok=True)
    manifest.to_csv(csv_out, index=False)
    write_report(manifest, Path(args.out_path), csv_out)
    print(Path(args.out_path).resolve())
    print(csv_out.resolve())


if __name__ == "__main__":
    main()
