from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


TABLE_SPECS = [
    {
        "table_id": "same_domain_anchor",
        "caption": "Same-domain anchors on the Ishu benchmark.",
        "label": "tab:same-domain-anchor",
        "columns": [
            ("row_label", "Method", "l"),
            ("accuracy", "Acc.", "r"),
            ("auc", "AUC", "r"),
        ],
    },
    {
        "table_id": "transfer_frontier",
        "caption": "Ishu to source-balanced MS COCOAI transfer and triage frontier.",
        "label": "tab:transfer-frontier",
        "columns": [
            ("row_label", "Method", "l"),
            ("accuracy", "Acc.", "r"),
            ("auc", "AUC", "r"),
            ("brier", "Brier", "r"),
            ("ece", "ECE", "r"),
            ("fake_call_rate", "Fake", "r"),
            ("coverage", "Cov.", "r"),
            ("decided_accuracy", "Dec.", "r"),
        ],
    },
    {
        "table_id": "reverse_operating_points",
        "caption": "MS COCOAI to Ishu reverse-transfer operating points.",
        "label": "tab:reverse-operating-points",
        "columns": [
            ("row_label", "Method", "l"),
            ("accuracy", "Acc.", "r"),
            ("auc", "AUC", "r"),
            ("brier", "Brier", "r"),
            ("ece", "ECE", "r"),
            ("fake_call_rate", "Fake", "r"),
        ],
    },
    {
        "table_id": "robustness_stress",
        "caption": "Reverse tuned-fusion robustness deltas relative to the clean source-capped operating point.",
        "label": "tab:robustness-stress",
        "columns": [
            ("row_label", "Condition", "l"),
            ("accuracy", "Acc.", "r"),
            ("delta_accuracy_vs_clean", "$\\Delta$Acc.", "r"),
            ("auc", "AUC", "r"),
            ("delta_auc_vs_clean", "$\\Delta$AUC", "r"),
            ("fake_call_rate", "Fake", "r"),
        ],
    },
    {
        "table_id": "source_holdout_stress",
        "caption": "Held-out generator stress for the source-capped reverse tuned-fusion policy.",
        "label": "tab:source-holdout-stress",
        "columns": [
            ("row_label", "Held-out", "l"),
            ("recall", "Recall", "r"),
            ("fake_miss_rate", "Miss", "r"),
            ("predicted_fake_rate", "Fake", "r"),
            ("utility", "Utility", "r"),
        ],
    },
]

ROW_LABELS = {
    "ishu_same_combined_v3": "combined_v3",
    "ishu_same_resnet18": "ResNet-18",
    "ishu_same_physics_guided": "Physics-guided",
    "ishu_to_ms_combined_v3": "combined_v3",
    "ishu_to_ms_resnet18": "ResNet-18",
    "ishu_to_ms_physics_guided": "Physics-guided",
    "ishu_to_ms_convnext_tiny_frozen": "ConvNeXt",
    "ishu_to_ms_scp_fusion_v0": "SCP-Fusion v0",
    "ishu_to_ms_scp_fusion_dinov2": "SCP-Fusion + DINOv2",
    "ishu_to_ms_scp_fusion_all_foundation": "SCP-Fusion + CLIP + DINOv2",
    "ishu_to_ms_clip_standalone": "CLIP",
    "ishu_to_ms_triage5_clip_standalone": "CLIP triage",
    "ms_to_ishu_physics_guided": "Physics-guided",
    "ms_to_ishu_clip_vit_b_32": "CLIP",
    "ms_to_ishu_score_fusion_all6_temp_balanced": "All-branch fusion",
    "ms_to_ishu_branch_dropout_auc": "Branch-dropout fusion",
    "ms_to_ishu_source_cap_accuracy": "Source-threshold cap",
    "ms_to_ishu_source_holdout_tuned_fusion": "Source-heldout tuned",
    "ms_to_ishu_tuned_fusion_constraint_sweep_best": "Clean cap 0.40",
    "ms_to_ishu_tuned_fusion_native_tiling_best": "Native-tiled v3",
    "ms_to_ishu_tuned_fusion_jpeg70": "JPEG70",
    "ms_to_ishu_tuned_fusion_jpeg50": "JPEG50",
    "ms_to_ishu_tuned_fusion_jpeg30": "JPEG30",
    "ms_to_ishu_tuned_fusion_noise3": "Noise3",
    "ms_to_ishu_tuned_fusion_social_square": "Social square",
    "ms_to_ishu_tuned_fusion_social_720p": "Social 720p",
    "ms_to_ishu_tuned_fusion_crop85": "Crop85",
    "ms_to_ishu_tuned_fusion_screenshot": "Screenshot",
    "ms_to_ishu_tuned_fusion_blur1": "Blur1",
    "ms_to_ishu_tuned_fusion_resize_half": "Resize half",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build LaTeX table fragments from compact submission result CSVs."
    )
    parser.add_argument(
        "--table-manifest",
        default="reports/assets/submission_result_table_manifest.csv",
        help="Manifest generated by build_submission_result_tables.py.",
    )
    parser.add_argument("--out-dir", default="reports/assets/latex_tables")
    parser.add_argument(
        "--report-out",
        default="reports/submission_latex_tables_2026_06_14.md",
        help="Markdown report listing generated LaTeX fragments.",
    )
    return parser.parse_args()


def _latex_escape(value: object) -> str:
    text = "" if value is None or pd.isna(value) else str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def _format_cell(value: object, *, signed: bool = False) -> str:
    if value is None or pd.isna(value):
        return "--"
    if isinstance(value, float):
        if signed:
            return f"{value:+.3f}"
        return f"{value:.3f}"
    return _latex_escape(value)


def _table_spec(table_id: str) -> dict[str, object]:
    for spec in TABLE_SPECS:
        if spec["table_id"] == table_id:
            return spec
    raise ValueError(f"No LaTeX table spec for table_id={table_id!r}")


def _row_label(row: pd.Series) -> str:
    if "finding_id" in row.index and not pd.isna(row["finding_id"]):
        finding_id = str(row["finding_id"])
        return ROW_LABELS.get(finding_id, str(row["method"]))
    if "heldout_source" in row.index and not pd.isna(row["heldout_source"]):
        return str(row["heldout_source"])
    return str(row.get("method", "row"))


def _tabular_spec(columns: list[tuple[str, str, str]]) -> str:
    return " ".join(spec for _column, _label, spec in columns)


def _latex_table(frame: pd.DataFrame, spec: dict[str, object]) -> str:
    columns = list(spec["columns"])
    table_frame = frame.copy()
    table_frame["row_label"] = [_row_label(row) for _index, row in table_frame.iterrows()]
    header = " & ".join(label for _column, label, _align in columns) + r" \\"
    body = []
    for row in table_frame.itertuples(index=False):
        row_data = row._asdict()
        cells = []
        for column, _label, _align in columns:
            signed = column.startswith("delta_")
            cells.append(_format_cell(row_data.get(column), signed=signed))
        body.append(" & ".join(cells) + r" \\")
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        rf"\caption{{{_latex_escape(spec['caption'])}}}",
        rf"\label{{{spec['label']}}}",
        rf"\begin{{tabular}}{{{_tabular_spec(columns)}}}",
        r"\toprule",
        header,
        r"\midrule",
        *body,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    return "\n".join(lines)


def build_latex_tables(table_manifest: Path, out_dir: Path) -> pd.DataFrame:
    manifest = pd.read_csv(table_manifest)
    out_dir.mkdir(parents=True, exist_ok=True)
    rows = []
    for manifest_row in manifest.itertuples(index=False):
        spec = _table_spec(manifest_row.table_id)
        source_path = Path(manifest_row.path)
        frame = pd.read_csv(source_path)
        tex = _latex_table(frame, spec)
        out_path = out_dir / f"{manifest_row.table_id}.tex"
        out_path.write_text(tex, encoding="utf-8")
        rows.append(
            {
                "table_id": manifest_row.table_id,
                "source_csv": source_path.as_posix(),
                "latex_path": out_path.as_posix(),
                "caption": spec["caption"],
                "n_rows": len(frame),
            }
        )
    latex_manifest = pd.DataFrame(rows)
    latex_manifest.to_csv(out_dir / "submission_latex_table_manifest.csv", index=False)
    return latex_manifest


def _markdown_table(frame: pd.DataFrame) -> str:
    columns = list(frame.columns)
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame.itertuples(index=False):
        lines.append("| " + " | ".join(str(value).replace("\n", " ") for value in row) + " |")
    return "\n".join(lines)


def write_report(latex_manifest: pd.DataFrame, report_out: Path) -> None:
    lines = [
        "# Submission LaTeX Tables",
        "",
        "Run date: 2026-06-14",
        "",
        "Generated by `scripts/build_submission_latex_tables.py` from compact submission result tables.",
        "",
        "The fragments assume the paper template supports `booktabs` commands (`\\toprule`, `\\midrule`, `\\bottomrule`). They are meant as starting points for WIFS/DFF drafting, not final camera-ready layout.",
        "",
        _markdown_table(latex_manifest),
        "",
    ]
    report_out.parent.mkdir(parents=True, exist_ok=True)
    report_out.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    latex_manifest = build_latex_tables(Path(args.table_manifest), Path(args.out_dir))
    write_report(latex_manifest, Path(args.report_out))
    print(Path(args.report_out).resolve())
    print((Path(args.out_dir) / "submission_latex_table_manifest.csv").resolve())


if __name__ == "__main__":
    main()
