from __future__ import annotations

import argparse
from datetime import date, timedelta
from pathlib import Path

import pandas as pd


DEFAULT_RUN_DATE = date.today()

STATUS_POLICY = {
    "missing_asset": {
        "phase": "repair",
        "priority": 0,
        "buffer_days": 14,
        "reason": "Referenced material is missing; repair before writing or export.",
    },
    "decision_needed": {
        "phase": "scope",
        "priority": 1,
        "buffer_days": 14,
        "reason": "A human choice still controls what evidence enters the upload.",
    },
    "writing_needed": {
        "phase": "draft",
        "priority": 2,
        "buffer_days": 10,
        "reason": "Generated prose exists, but the venue-ready draft still needs author editing.",
    },
    "final_export_needed": {
        "phase": "export",
        "priority": 3,
        "buffer_days": 3,
        "reason": "Source artifacts exist, but the actual upload file has not been finalized.",
    },
}

CRITICAL_PATH_COLUMNS = [
    "venue_key",
    "venue",
    "deadline",
    "packet_status",
    "phase",
    "priority",
    "item",
    "status",
    "target_done_by",
    "days_until_target",
    "urgency",
    "days_until_deadline",
    "reason",
    "action",
    "paths",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a deadline-driven critical path from the submission upload checklist."
    )
    parser.add_argument(
        "--checklist",
        default="reports/assets/submission_upload_checklist.csv",
        help="Machine-readable upload checklist generated by build_submission_upload_checklist.py.",
    )
    parser.add_argument(
        "--scorecard",
        default="reports/assets/submission_scorecard.csv",
        help="Venue scorecard generated by build_submission_scorecard.py.",
    )
    parser.add_argument(
        "--out-path",
        default="reports/submission_critical_path_2026_06_14.md",
        help="Markdown critical-path report to write.",
    )
    parser.add_argument(
        "--csv-out",
        default="reports/assets/submission_critical_path.csv",
        help="Machine-readable critical-path CSV to write.",
    )
    parser.add_argument(
        "--run-date",
        default=DEFAULT_RUN_DATE.isoformat(),
        help="Date used for deadline countdowns, in YYYY-MM-DD format. Defaults to today's local date.",
    )
    return parser.parse_args()


def _target_date(deadline: str, status: str) -> date:
    policy = STATUS_POLICY[status]
    return date.fromisoformat(deadline) - timedelta(days=int(policy["buffer_days"]))


def _urgency(days_until_target: int) -> str:
    if days_until_target < 0:
        return "overdue"
    if days_until_target <= 3:
        return "due_now"
    if days_until_target <= 7:
        return "due_this_week"
    if days_until_target <= 14:
        return "due_next_two_weeks"
    return "scheduled"


def build_critical_path(
    checklist_path: Path,
    scorecard_path: Path,
    run_date: date = DEFAULT_RUN_DATE,
) -> tuple[str, pd.DataFrame]:
    checklist = pd.read_csv(checklist_path)
    scorecard = pd.read_csv(scorecard_path)
    scorecard_by_key = scorecard.set_index("venue_key")
    pending = checklist[checklist["status"].isin(STATUS_POLICY)].copy()

    rows = []
    for item in pending.itertuples(index=False):
        policy = STATUS_POLICY[str(item.status)]
        target = _target_date(str(item.deadline), str(item.status))
        days_until_target = (target - run_date).days
        score = scorecard_by_key.loc[str(item.venue_key)]
        rows.append(
            {
                "venue_key": item.venue_key,
                "venue": item.venue,
                "deadline": item.deadline,
                "packet_status": score["packet_status"],
                "phase": policy["phase"],
                "priority": policy["priority"],
                "item": item.item,
                "status": item.status,
                "target_done_by": target.isoformat(),
                "days_until_target": days_until_target,
                "urgency": _urgency(days_until_target),
                "days_until_deadline": (date.fromisoformat(str(item.deadline)) - run_date).days,
                "reason": policy["reason"],
                "action": item.action,
                "paths": item.paths,
            }
        )

    critical_path = pd.DataFrame(rows, columns=CRITICAL_PATH_COLUMNS).sort_values(
        ["target_done_by", "priority", "deadline", "venue_key", "item"],
        ignore_index=True,
    )
    return _write_markdown(critical_path, run_date), critical_path


def _markdown_escape(value: object) -> str:
    if value is None or pd.isna(value):
        return ""
    return str(value).replace("\n", " ").replace("|", "\\|")


def _markdown_table(frame: pd.DataFrame, columns: list[str]) -> str:
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame[columns].itertuples(index=False):
        lines.append("| " + " | ".join(_markdown_escape(value) for value in row) + " |")
    return "\n".join(lines)


def _venue_summary(frame: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for venue, group in frame.groupby("venue", sort=False):
        counts = group["status"].value_counts().to_dict()
        rows.append(
            {
                "venue": venue,
                "deadline": group.iloc[0]["deadline"],
                "packet_status": group.iloc[0]["packet_status"],
                "pending_items": len(group),
                "writing_needed": counts.get("writing_needed", 0),
                "final_export_needed": counts.get("final_export_needed", 0),
                "first_target": group["target_done_by"].min(),
                "last_target": group["target_done_by"].max(),
            }
        )
    return pd.DataFrame(
        rows,
        columns=[
            "venue",
            "deadline",
            "packet_status",
            "pending_items",
            "writing_needed",
            "final_export_needed",
            "first_target",
            "last_target",
        ],
    )


def _write_markdown(frame: pd.DataFrame, run_date: date) -> str:
    summary = _venue_summary(frame)
    columns = [
        "venue_key",
        "phase",
        "item",
        "status",
        "target_done_by",
        "days_until_target",
        "urgency",
        "action",
    ]
    lines = [
        "# Submission Critical Path",
        "",
        f"Run date: {run_date.isoformat()}",
        "",
        "Generated by `scripts/build_submission_critical_path.py` from the upload checklist and submission scorecard.",
        "",
        "This report is the remaining work queue after the checked-in packet has reached `ready_to_polish`; it does not change benchmark claims.",
        "",
        "## Venue Summary",
        "",
        _markdown_table(summary, list(summary.columns)),
        "",
        "## Ordered Critical Path",
        "",
        _markdown_table(frame, columns),
        "",
        "## Policy",
        "",
        "- `writing_needed` targets are set 10 days before the venue deadline.",
        "- `final_export_needed` targets are set 3 days before the venue deadline.",
        "- Missing assets or unresolved decisions, if any appear later, are pulled earlier with larger buffers.",
        "- Urgency bands are `overdue`, `due_now` (0-3 days), `due_this_week` (4-7 days), `due_next_two_weeks` (8-14 days), and `scheduled`.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    text, critical_path = build_critical_path(
        Path(args.checklist),
        Path(args.scorecard),
        date.fromisoformat(args.run_date),
    )
    out_path = Path(args.out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    csv_path = Path(args.csv_out)
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    critical_path.to_csv(csv_path, index=False)
    print(out_path.resolve())
    print(csv_path.resolve())


if __name__ == "__main__":
    main()
