from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from forensic_compare.conventional import feature_names  # noqa: E402


RUN_DATE = "2026-06-14"

FAMILY_DESCRIPTIONS = {
    "resize_residual": "Bicubic downsample/upsample residuals inherited from reconstruction_lite.",
    "fft_lowpass_residual": "Residuals after reconstructing the image from low-frequency FFT coefficients.",
    "svd_lowrank_residual": "Residuals after reconstructing each color channel with a low-rank SVD approximation.",
    "cross_reconstructor_delta": "Deltas and ratios comparing reconstruction residual families and strengths.",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Document the reconstruction_v2 feature family."
    )
    parser.add_argument(
        "--out-path",
        default="reports/reconstruction_v2_feature_set_2026_06_14.md",
        help="Markdown report to write.",
    )
    parser.add_argument(
        "--csv-out",
        default="reports/assets/reconstruction_v2_feature_manifest.csv",
        help="Machine-readable feature manifest to write.",
    )
    return parser.parse_args()


def _family(name: str) -> str:
    if name.startswith("recon_half") or name.startswith("recon_quarter"):
        return "resize_residual"
    if name.startswith("recon_fft") and ("delta" not in name and "ratio" not in name):
        return "fft_lowpass_residual"
    if name.startswith("recon_svd") and ("delta" not in name and "ratio" not in name):
        return "svd_lowrank_residual"
    return "cross_reconstructor_delta"


def _description(name: str) -> str:
    family = _family(name)
    if name.endswith("_abs_mean"):
        statistic = "mean absolute RGB residual"
    elif name.endswith("_abs_p95"):
        statistic = "95th percentile absolute RGB residual"
    elif name.endswith("_luma_chroma_ratio"):
        statistic = "luma-to-chroma residual ratio"
    elif name.endswith("_laplacian_abs_mean"):
        statistic = "mean absolute Laplacian of the residual map"
    elif name.endswith("_tile16_std_mean"):
        statistic = "mean 16x16 tile residual standard deviation"
    elif name.endswith("_tile16_std_p90"):
        statistic = "90th percentile 16x16 tile residual standard deviation"
    elif name.endswith("_delta"):
        statistic = "cross-reconstruction delta"
    elif name.endswith("_ratio"):
        statistic = "cross-reconstruction ratio"
    else:
        statistic = "reconstruction residual statistic"
    return f"{statistic} for the {family.replace('_', ' ')} branch."


def build_manifest() -> pd.DataFrame:
    rows = []
    lite_features = set(feature_names("reconstruction_lite"))
    for index, name in enumerate(feature_names("reconstruction_v2"), start=1):
        family = _family(name)
        rows.append(
            {
                "order": index,
                "feature_name": name,
                "family": family,
                "description": _description(name),
                "status": (
                    "inherited_from_reconstruction_lite"
                    if name in lite_features
                    else "implemented_reconstruction_v2_ablation"
                ),
            }
        )
    return pd.DataFrame(rows)


def _markdown_escape(value: object) -> str:
    if value is None or pd.isna(value):
        return ""
    return str(value).replace("\n", " ").replace("|", "\\|")


def _markdown_table(frame: pd.DataFrame, columns: list[str]) -> str:
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame[columns].itertuples(index=False):
        lines.append("| " + " | ".join(_markdown_escape(value) for value in row) + " |")
    return "\n".join(lines)


def write_report(manifest: pd.DataFrame, out_path: Path, csv_out: Path) -> None:
    family_counts = manifest.groupby("family", sort=False).size().reset_index(name="feature_count")
    family_counts["description"] = family_counts["family"].map(FAMILY_DESCRIPTIONS)
    lines = [
        "# reconstruction_v2 Feature Set",
        "",
        f"Run date: {RUN_DATE}",
        "",
        "Generated by `scripts/build_reconstruction_v2_feature_report.py` from `forensic_compare.conventional.feature_names(\"reconstruction_v2\")`.",
        "",
        "`reconstruction_v2` extends `reconstruction_lite` with deterministic compression-style residuals. It adds FFT low-pass reconstructions and per-channel low-rank SVD reconstructions so the project can test autoencoder-like residual signals without downloading a learned reconstructor. This is still an ablation branch; it is not a claim of AEROBLADE/FIRE parity.",
        "",
        "## How To Run",
        "",
        "```powershell",
        "python scripts/run_feature_baseline.py `",
        "  --data-dir data/raw/ishu-2024-ai-generated-vs-real-images/dataset `",
        "  --output-dir runs/reconstruction_v2_probe/seed7 `",
        "  --feature-set reconstruction_v2 `",
        "  --classifier logistic_regression `",
        "  --seed 7",
        "```",
        "",
        "For a physics-guided neural ablation, pass `--physics-feature-set reconstruction_v2` to `scripts/train_physics_guided_net.py`. Historical `reconstruction_lite`, `combined_v3`, and `combined_v4` definitions are unchanged.",
        "",
        "## Feature Families",
        "",
        _markdown_table(family_counts, ["family", "feature_count", "description"]),
        "",
        "## Manifest",
        "",
        _markdown_table(manifest, ["order", "feature_name", "family", "description", "status"]),
        "",
        f"Machine-readable manifest: `{csv_out.as_posix()}`",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    manifest = build_manifest()
    csv_out = Path(args.csv_out)
    csv_out.parent.mkdir(parents=True, exist_ok=True)
    manifest.to_csv(csv_out, index=False)
    write_report(manifest, Path(args.out_path), csv_out)
    print(Path(args.out_path).resolve())
    print(csv_out.resolve())


if __name__ == "__main__":
    main()
