from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import pandas as pd


TRANSFER_SAME_DOMAIN = [
    ("ishu_same_combined_v3", "combined_v3"),
    ("ishu_same_resnet18", "ResNet-18"),
    ("ishu_same_physics_guided", "Physics-guided"),
]

TRANSFER_CROSS_DOMAIN = [
    ("ishu_to_ms_physics_guided", "Physics-guided"),
    ("ishu_to_ms_convnext_tiny_frozen", "Frozen ConvNeXt"),
    ("ishu_to_ms_scp_fusion_all_foundation", "SCP-Fusion all-foundation"),
    ("ishu_to_ms_clip_standalone", "Frozen CLIP"),
]

TRIAGE_CALLOUT = "ishu_to_ms_triage5_clip_standalone"

ROBUSTNESS_ROWS = [
    ("ms_to_ishu_tuned_fusion_constraint_sweep_best", "clean"),
    ("ms_to_ishu_tuned_fusion_jpeg70", "JPEG70"),
    ("ms_to_ishu_tuned_fusion_jpeg50", "JPEG50"),
    ("ms_to_ishu_tuned_fusion_jpeg30", "JPEG30"),
    ("ms_to_ishu_tuned_fusion_noise3", "noise3"),
    ("ms_to_ishu_tuned_fusion_social_square", "social"),
    ("ms_to_ishu_tuned_fusion_social_720p", "social720"),
    ("ms_to_ishu_tuned_fusion_crop85", "crop85"),
    ("ms_to_ishu_tuned_fusion_screenshot", "screen"),
    ("ms_to_ishu_tuned_fusion_blur1", "blur1"),
    ("ms_to_ishu_tuned_fusion_resize_half", "resize"),
]

BLUE = "#2E6F95"
ORANGE = "#D07C2C"
GREEN = "#2F8A5B"
INK = "#17212B"
GRID = "#D8DEE6"
PANEL = "#F8FAFC"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build large DFRWS poster-native panels from checked-in result tables."
    )
    parser.add_argument(
        "--core-results",
        default="reports/assets/publication_core_results.csv",
        help="Publication core result table generated by build_publication_tables.py.",
    )
    parser.add_argument(
        "--out-dir",
        default="reports/assets",
        help="Directory for poster panel PNG/SVG/CSV files.",
    )
    parser.add_argument(
        "--report-out",
        default="reports/dfrws_poster_native_figures_2026_06_13.md",
        help="Markdown report describing the generated poster-native panels.",
    )
    parser.add_argument("--dpi", type=int, default=220, help="PNG output DPI.")
    return parser.parse_args()


def _find_row(frame: pd.DataFrame, finding_id: str) -> pd.Series:
    matches = frame[frame["finding_id"] == finding_id]
    if matches.empty:
        raise ValueError(f"Missing finding_id={finding_id!r}")
    return matches.iloc[0]


def _metric(row: pd.Series, column: str) -> float | None:
    value = row.get(column)
    if pd.isna(value):
        return None
    return float(value)


def _panel_frame(
    core: pd.DataFrame, specs: list[tuple[str, str]], panel: str
) -> pd.DataFrame:
    rows = []
    for finding_id, label in specs:
        source = _find_row(core, finding_id)
        rows.append(
            {
                "panel": panel,
                "label": label,
                "finding_id": finding_id,
                "accuracy": _metric(source, "accuracy"),
                "auc": _metric(source, "auc"),
                "brier": _metric(source, "brier"),
                "ece": _metric(source, "ece"),
                "predicted_fake_rate": _metric(source, "predicted_fake_rate"),
                "coverage": _metric(source, "coverage"),
                "decided_accuracy": _metric(source, "decided_accuracy"),
            }
        )
    return pd.DataFrame(rows)


def _value_label(value: float | None) -> str:
    if value is None:
        return ""
    return f"{value:.3f}"


def _style_axis(ax: plt.Axes) -> None:
    ax.set_facecolor(PANEL)
    ax.grid(axis="x", color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)
    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.tick_params(axis="both", colors=INK, labelsize=11)


def _save_both(fig: plt.Figure, stem: Path, dpi: int) -> tuple[Path, Path]:
    png = stem.with_suffix(".png")
    svg = stem.with_suffix(".svg")
    fig.savefig(png, dpi=dpi, bbox_inches="tight", facecolor="white")
    fig.savefig(svg, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    return png, svg


def build_transfer_panel(core: pd.DataFrame, out_dir: Path, dpi: int) -> tuple[pd.DataFrame, Path, Path]:
    same = _panel_frame(core, TRANSFER_SAME_DOMAIN, "Ishu same-domain")
    transfer = _panel_frame(core, TRANSFER_CROSS_DOMAIN, "Ishu -> MS COCOAI")
    triage = _panel_frame(core, [(TRIAGE_CALLOUT, "Frozen CLIP triage")], "5% source-heldout triage")
    data = pd.concat([same, transfer, triage], ignore_index=True)

    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "svg.fonttype": "none",
            "axes.titleweight": "bold",
        }
    )
    fig, axes = plt.subplots(1, 2, figsize=(15.5, 7.2), constrained_layout=True)
    fig.suptitle(
        "Poster panel: same-domain accuracy is not transfer reliability",
        fontsize=19,
        color=INK,
        fontweight="bold",
    )

    for ax, frame, title, subtitle in [
        (
            axes[0],
            same,
            "Ishu same-domain",
            "Physics-guided fusion is the in-domain anchor.",
        ),
        (
            axes[1],
            transfer,
            "Ishu -> source-balanced MS COCOAI",
            "Frozen CLIP is the current transfer-ranking frontier.",
        ),
    ]:
        _style_axis(ax)
        y = list(range(len(frame)))
        height = 0.34
        ax.barh(
            [pos + height / 2 for pos in y],
            frame["accuracy"].astype(float),
            height=height,
            color=BLUE,
            label="Accuracy",
        )
        ax.barh(
            [pos - height / 2 for pos in y],
            frame["auc"].astype(float),
            height=height,
            color=ORANGE,
            label="AUC",
        )
        ax.set_yticks(y)
        ax.set_yticklabels(frame["label"])
        ax.invert_yaxis()
        ax.set_xlim(0.50, 0.96)
        ax.set_xlabel("score", color=INK, fontsize=11)
        ax.set_title(title, fontsize=15, color=INK, loc="left", pad=24)
        ax.text(
            0.0,
            1.02,
            subtitle,
            transform=ax.transAxes,
            fontsize=11,
            color="#4A5568",
            va="bottom",
        )
        for pos, acc, auc in zip(y, frame["accuracy"], frame["auc"], strict=True):
            ax.text(float(acc) + 0.008, pos + height / 2, _value_label(acc), va="center", fontsize=10, color=INK)
            ax.text(float(auc) + 0.008, pos - height / 2, _value_label(auc), va="center", fontsize=10, color=INK)
        ax.legend(frameon=False, loc="lower right", fontsize=10)

    triage_row = triage.iloc[0]
    fig.text(
        0.51,
        0.04,
        (
            "Strict triage callout: frozen CLIP decides on "
            f"{triage_row['coverage']:.1%} of held-out-source target images at "
            f"{triage_row['decided_accuracy']:.1%} decided-case accuracy."
        ),
        ha="center",
        va="bottom",
        fontsize=12,
        color=INK,
        bbox={"boxstyle": "round,pad=0.45", "facecolor": "#EEF5F8", "edgecolor": "#B8CEDA"},
    )

    csv_path = out_dir / "dfrws_poster_transfer_panel.csv"
    data.to_csv(csv_path, index=False)
    png_path, svg_path = _save_both(fig, out_dir / "dfrws_poster_transfer_panel", dpi)
    return data, png_path, svg_path


def build_robustness_panel(core: pd.DataFrame, out_dir: Path, dpi: int) -> tuple[pd.DataFrame, Path, Path]:
    data = _panel_frame(core, ROBUSTNESS_ROWS, "MS COCOAI -> Ishu tuned fusion robustness")

    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "svg.fonttype": "none",
            "axes.titleweight": "bold",
        }
    )
    fig, ax = plt.subplots(figsize=(15.5, 7.2))
    fig.subplots_adjust(left=0.075, right=0.985, top=0.84, bottom=0.15)
    fig.suptitle(
        "Poster panel: processing shift changes ranking and fake-call behavior",
        fontsize=18,
        color=INK,
        fontweight="bold",
        x=0.075,
        y=0.97,
        ha="left",
    )
    fig.text(
        0.075,
        0.915,
        "Reverse tuned fusion with source fake-rate cap 0.40; all values are target means over three seeds.",
        fontsize=12,
        color="#4A5568",
        va="bottom",
    )
    _style_axis(ax)
    x = list(range(len(data)))
    ax.plot(x, data["auc"].astype(float), color=ORANGE, marker="o", linewidth=3, label="AUC")
    ax.plot(x, data["accuracy"].astype(float), color=BLUE, marker="o", linewidth=3, label="Accuracy")
    ax.plot(
        x,
        data["predicted_fake_rate"].astype(float),
        color=GREEN,
        marker="o",
        linewidth=3,
        label="Fake-call rate",
    )
    ax.axhline(0.50, color="#8B97A6", linewidth=1.2, linestyle="--")
    ax.set_ylim(0.20, 0.92)
    ax.set_xticks(x)
    ax.set_xticklabels(data["label"], rotation=0)
    ax.set_ylabel("mean score or rate", color=INK, fontsize=12)
    for idx, row in data.iterrows():
        ax.text(idx, float(row["auc"]) + 0.018, f"{row['auc']:.3f}", ha="center", fontsize=9, color=INK)
        ax.text(
            idx,
            float(row["predicted_fake_rate"]) - 0.035,
            f"{row['predicted_fake_rate']:.3f}",
            ha="center",
            fontsize=9,
            color=INK,
        )
    ax.legend(frameon=False, loc="upper right", fontsize=11)
    ax.text(
        0.02,
        0.06,
        "Read this panel as a stress test, not a final production guarantee: blur, resize, and harsh JPEG still move the operating point.",
        transform=ax.transAxes,
        fontsize=11,
        color=INK,
        bbox={"boxstyle": "round,pad=0.42", "facecolor": "#FFF5E8", "edgecolor": "#E2C198"},
    )

    csv_path = out_dir / "dfrws_poster_robustness_panel.csv"
    data.to_csv(csv_path, index=False)
    png_path, svg_path = _save_both(fig, out_dir / "dfrws_poster_robustness_panel", dpi)
    return data, png_path, svg_path


def build_report(
    report_out: Path,
    transfer_png: Path,
    transfer_svg: Path,
    robustness_png: Path,
    robustness_svg: Path,
) -> str:
    def link(path: Path) -> str:
        try:
            return path.relative_to(report_out.parent).as_posix()
        except ValueError:
            return path.as_posix()

    text = "\n".join(
        [
            "# DFRWS Poster-Native Figure Pack",
            "",
            "Run date: 2026-06-13",
            "",
            "Generated by `scripts/build_dfrws_poster_figures.py` from `reports/assets/publication_core_results.csv`.",
            "",
            "These panels are intentionally simpler than the paper figures: large labels, few metrics, and SVG exports with live text for poster editing.",
            "",
            "## Files",
            "",
            "| panel | PNG | SVG | CSV |",
            "| --- | --- | --- | --- |",
            f"| transfer headline | `{transfer_png.as_posix()}` | `{transfer_svg.as_posix()}` | `reports/assets/dfrws_poster_transfer_panel.csv` |",
            f"| robustness stress | `{robustness_png.as_posix()}` | `{robustness_svg.as_posix()}` | `reports/assets/dfrws_poster_robustness_panel.csv` |",
            "",
            "## Transfer Panel",
            "",
            f"![DFRWS transfer panel]({link(transfer_png)})",
            "",
            "This panel keeps the poster claim crisp: physics-guided fusion improves the same-domain anchor, but frozen CLIP is the cross-domain ranking and strict-triage frontier.",
            "",
            "## Robustness Panel",
            "",
            f"![DFRWS robustness panel]({link(robustness_png)})",
            "",
            "This panel makes the caveat visible: the source-capped reverse fusion setting is useful, but blur, resize, screenshots, and harsh recompression still shift ranking and fake-call behavior.",
            "",
            "## Suggested Poster Swap",
            "",
            "Replace the two dense embedded figures in the first poster draft with these two poster-native panels, then keep the older paper figures in the appendix/report package.",
            "",
        ]
    )
    report_out.parent.mkdir(parents=True, exist_ok=True)
    report_out.write_text(text, encoding="utf-8")
    return text


def main() -> None:
    args = parse_args()
    core = pd.read_csv(args.core_results)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    report_out = Path(args.report_out)

    _transfer, transfer_png, transfer_svg = build_transfer_panel(core, out_dir, args.dpi)
    _robustness, robustness_png, robustness_svg = build_robustness_panel(core, out_dir, args.dpi)
    build_report(report_out, transfer_png, transfer_svg, robustness_png, robustness_svg)

    print(transfer_png.resolve())
    print(transfer_svg.resolve())
    print(robustness_png.resolve())
    print(robustness_svg.resolve())
    print(report_out.resolve())


if __name__ == "__main__":
    main()
