from __future__ import annotations

import argparse
import hashlib
from datetime import date
from pathlib import Path

import pandas as pd


DEFAULT_RUN_DATE = date.today()
DEFAULT_SKIP_RELATIVE_PATHS = {
    "reports/submission_artifact_hashes_2026_06_15.md",
    "reports/assets/submission_artifact_hashes.csv",
    "reports/submission_artifact_hashes_lint_2026_06_15.md",
    "reports/assets/submission_artifact_hashes_lint.csv",
    "reports/submission_privacy_audit_2026_06_15.md",
    "reports/assets/submission_privacy_audit.csv",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build SHA-256 hashes for artifacts listed in the submission packet manifest."
    )
    parser.add_argument("--repo-root", default=".", help="Repository root for resolving manifest paths.")
    parser.add_argument(
        "--manifest",
        default="reports/assets/submission_packet_manifest.csv",
        help="Submission packet manifest generated by build_submission_packet.py.",
    )
    parser.add_argument(
        "--out-path",
        default="reports/submission_artifact_hashes_2026_06_15.md",
        help="Markdown hash summary to write.",
    )
    parser.add_argument(
        "--hashes-out",
        default="reports/assets/submission_artifact_hashes.csv",
        help="Machine-readable artifact hash CSV to write.",
    )
    parser.add_argument(
        "--run-date",
        default=DEFAULT_RUN_DATE.isoformat(),
        help="Date to stamp into the report, in YYYY-MM-DD format. Defaults to today's local date.",
    )
    return parser.parse_args()


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _markdown_escape(value: object) -> str:
    if value is None or pd.isna(value):
        return ""
    return str(value).replace("\n", " ").replace("|", "\\|")


def _markdown_table(frame: pd.DataFrame, columns: list[str]) -> str:
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame[columns].itertuples(index=False):
        lines.append("| " + " | ".join(_markdown_escape(value) for value in row) + " |")
    return "\n".join(lines)


def _resolve_repo_path(repo_root: Path, path: Path) -> Path:
    return path if path.is_absolute() else repo_root / path


def _repo_relative(repo_root: Path, path: Path) -> str:
    try:
        return path.resolve().relative_to(repo_root).as_posix()
    except ValueError:
        return path.as_posix()


def build_artifact_hashes(
    repo_root: Path,
    manifest_path: Path,
    out_path: Path,
    hashes_out: Path,
    run_date: date = DEFAULT_RUN_DATE,
) -> tuple[str, pd.DataFrame]:
    repo_root = repo_root.resolve()
    manifest_path = _resolve_repo_path(repo_root, manifest_path)
    out_path = _resolve_repo_path(repo_root, out_path)
    hashes_out = _resolve_repo_path(repo_root, hashes_out)
    manifest = pd.read_csv(manifest_path)
    output_relpaths = {
        _repo_relative(repo_root, manifest_path),
        _repo_relative(repo_root, out_path),
        _repo_relative(repo_root, hashes_out),
        *DEFAULT_SKIP_RELATIVE_PATHS,
    }
    rows = []
    for artifact in manifest.itertuples(index=False):
        relative_path = str(artifact.path)
        full_path = repo_root / relative_path
        exists = full_path.exists()
        skipped = relative_path in output_relpaths
        rows.append(
            {
                "path": relative_path,
                "type": artifact.type,
                "venues": artifact.venues,
                "required": bool(artifact.required),
                "exists": bool(exists),
                "size_bytes": int(full_path.stat().st_size) if exists else pd.NA,
                "sha256": _sha256_file(full_path) if exists and not skipped else pd.NA,
                "hash_status": "index_or_self_skipped" if skipped else "hashed" if exists else "missing",
            }
        )
    hashes = pd.DataFrame(rows)

    hashes_out.parent.mkdir(parents=True, exist_ok=True)
    hashes.to_csv(hashes_out, index=False)

    summary = (
        hashes.groupby("type", dropna=False)
        .agg(
            artifacts=("path", "count"),
            present=("exists", "sum"),
            hashed=("hash_status", lambda values: int((values == "hashed").sum())),
            bytes=("size_bytes", "sum"),
        )
        .reset_index()
    )
    status_counts = hashes["hash_status"].value_counts().rename_axis("hash_status").reset_index(name="artifacts")
    missing = hashes[~hashes["exists"]][["path", "type", "required"]]
    lines = [
        "# Submission Artifact Hashes",
        "",
        f"Run date: {run_date.isoformat()}",
        "",
        "Generated by `scripts/build_submission_artifact_hashes.py` from `reports/assets/submission_packet_manifest.csv`.",
        "",
        "This report provides SHA-256 hashes for checked-in submission packet artifacts so a reviewer or coauthor can verify they are looking at the same files. The source manifest plus the report and CSV hash outputs skip their own hashes to avoid self-referential churn.",
        "",
        "## Status",
        "",
        _markdown_table(status_counts, ["hash_status", "artifacts"]),
        "",
        "## By Artifact Type",
        "",
        _markdown_table(summary, ["type", "artifacts", "present", "hashed", "bytes"]),
        "",
        "## Missing Artifacts",
        "",
        "None." if missing.empty else _markdown_table(missing, ["path", "type", "required"]),
        "",
        f"Machine-readable hashes: `{_repo_relative(repo_root, hashes_out)}`",
        "",
    ]
    text = "\n".join(lines)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    return text, hashes


def main() -> None:
    args = parse_args()
    text, hashes = build_artifact_hashes(
        repo_root=Path(args.repo_root),
        manifest_path=Path(args.manifest),
        out_path=Path(args.out_path),
        hashes_out=Path(args.hashes_out),
        run_date=date.fromisoformat(args.run_date),
    )
    print(Path(args.out_path).resolve())
    print(Path(args.hashes_out).resolve())
    if hashes["exists"].isna().any():
        raise SystemExit("Artifact hash table contains invalid existence values")
    if not text:
        raise SystemExit("No report text generated")


if __name__ == "__main__":
    main()
