from __future__ import annotations

import argparse
import re
from datetime import date
from pathlib import Path

import pandas as pd


DEFAULT_RUN_DATE = date.today()
BINARY_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp", ".pptx", ".pdf"}
DEFAULT_SKIP_RELATIVE_PATHS = {
    "reports/submission_privacy_audit_2026_06_15.md",
    "reports/assets/submission_privacy_audit.csv",
}
LOCAL_USER_PATH = re.compile(r"(?i)([A-Z]:[\\/]+Users[\\/]+(?!<you>)[^\\/,\s;:\"'<>]+[\\/]+[^\s,;\"'<>]*)")
PLACEHOLDER_USER_PATH = re.compile(r"(?i)[A-Z]:[\\/]+Users[\\/]+<you>[\\/]+")
SECRET_ASSIGNMENT = re.compile(
    r"(?i)\b(api[_-]?key|secret|token|password|aws_access_key_id|github_token|kaggle_key)\b\s*[:=]\s*['\"]?([A-Za-z0-9_\-]{12,})"
)
MACHINE_READABLE_TYPES = {
    "result-data",
    "table",
    "quality-control",
    "planning",
    "claim-audit",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Audit submission packet artifacts for local absolute paths and obvious secret-like strings."
    )
    parser.add_argument("--repo-root", default=".", help="Repository root for resolving artifact paths.")
    parser.add_argument(
        "--manifest",
        default="reports/assets/submission_packet_manifest.csv",
        help="Submission packet manifest generated by build_submission_packet.py.",
    )
    parser.add_argument(
        "--out-path",
        default="reports/submission_privacy_audit_2026_06_15.md",
        help="Markdown audit report to write.",
    )
    parser.add_argument(
        "--findings-out",
        default="reports/assets/submission_privacy_audit.csv",
        help="Machine-readable audit findings to write.",
    )
    parser.add_argument(
        "--run-date",
        default=DEFAULT_RUN_DATE.isoformat(),
        help="Date to stamp into the report, in YYYY-MM-DD format. Defaults to today's local date.",
    )
    return parser.parse_args()


def _markdown_escape(value: object) -> str:
    if value is None or pd.isna(value):
        return ""
    return str(value).replace("\n", " ").replace("|", "\\|")


def _markdown_table(frame: pd.DataFrame, columns: list[str]) -> str:
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame[columns].itertuples(index=False):
        lines.append("| " + " | ".join(_markdown_escape(value) for value in row) + " |")
    return "\n".join(lines)


def _snippet(text: str, start: int, end: int) -> str:
    left = max(0, start - 60)
    right = min(len(text), end + 60)
    return text[left:right].replace("\r", " ").replace("\n", " ")


def _line_number(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def _resolve_repo_path(repo_root: Path, path: Path) -> Path:
    return path if path.is_absolute() else repo_root / path


def _repo_relative(repo_root: Path, path: Path) -> str:
    try:
        return path.resolve().relative_to(repo_root).as_posix()
    except ValueError:
        return path.as_posix()


def _severity(issue: str, artifact_type: str) -> str:
    if issue == "secret_like_assignment":
        return "blocker"
    if issue == "local_absolute_path" and artifact_type in MACHINE_READABLE_TYPES:
        return "warning"
    return "blocker"


def build_privacy_audit(
    repo_root: Path,
    manifest_path: Path,
    out_path: Path,
    findings_out: Path,
    run_date: date = DEFAULT_RUN_DATE,
) -> tuple[str, pd.DataFrame]:
    repo_root = repo_root.resolve()
    manifest_path = _resolve_repo_path(repo_root, manifest_path)
    out_path = _resolve_repo_path(repo_root, out_path)
    findings_out = _resolve_repo_path(repo_root, findings_out)
    output_relpaths = {
        _repo_relative(repo_root, out_path),
        _repo_relative(repo_root, findings_out),
        *DEFAULT_SKIP_RELATIVE_PATHS,
    }
    manifest = pd.read_csv(manifest_path)
    rows: list[dict[str, object]] = []
    scanned = 0
    skipped_binary = 0
    skipped_output = 0

    for artifact in manifest.itertuples(index=False):
        relative_path = str(artifact.path)
        full_path = repo_root / relative_path
        if relative_path in output_relpaths:
            skipped_output += 1
            continue
        if not full_path.exists() or full_path.suffix.lower() in BINARY_SUFFIXES:
            skipped_binary += int(full_path.exists() and full_path.suffix.lower() in BINARY_SUFFIXES)
            continue
        try:
            text = full_path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        scanned += 1
        artifact_type = str(artifact.type)
        placeholder_count = len(PLACEHOLDER_USER_PATH.findall(text))

        for match in LOCAL_USER_PATH.finditer(text):
            rows.append(
                {
                    "path": relative_path,
                    "type": artifact_type,
                    "issue": "local_absolute_path",
                    "severity": _severity("local_absolute_path", artifact_type),
                    "line": _line_number(text, match.start()),
                    "example": _snippet(text, match.start(), match.end()),
                }
            )
        for match in SECRET_ASSIGNMENT.finditer(text):
            rows.append(
                {
                    "path": relative_path,
                    "type": artifact_type,
                    "issue": "secret_like_assignment",
                    "severity": "blocker",
                    "line": _line_number(text, match.start()),
                    "example": _snippet(text, match.start(), match.end()),
                }
            )
        if placeholder_count:
            rows.append(
                {
                    "path": relative_path,
                    "type": artifact_type,
                    "issue": "placeholder_local_path",
                    "severity": "info",
                    "line": "",
                    "example": f"{placeholder_count} placeholder path example(s), such as C:\\Users\\<you>\\...",
                }
            )

    findings = pd.DataFrame(
        rows,
        columns=["path", "type", "issue", "severity", "line", "example"],
    )
    findings_out.parent.mkdir(parents=True, exist_ok=True)
    findings.to_csv(findings_out, index=False)

    if findings.empty:
        summary = pd.DataFrame(columns=["severity", "issue", "findings"])
        status = "PASS"
    else:
        summary = (
            findings.groupby(["severity", "issue"], dropna=False)
            .size()
            .reset_index(name="findings")
            .sort_values(["severity", "issue"])
        )
        status = "PASS" if "blocker" not in set(findings["severity"]) else "REVIEW"

    blocker_frame = findings[findings["severity"] == "blocker"].head(20)
    warning_frame = findings[findings["severity"] == "warning"].head(20)
    lines = [
        "# Submission Privacy Audit",
        "",
        f"Run date: {run_date.isoformat()}",
        "",
        f"Status: **{status}**.",
        "",
        "Generated by `scripts/build_submission_privacy_audit.py` from the submission packet manifest.",
        "",
        f"Scanned `{scanned}` text artifacts, skipped `{skipped_binary}` binary/media artifacts, and skipped `{skipped_output}` privacy-audit output artifacts.",
        "",
        "The audit treats obvious secret-like assignments and local absolute paths in narrative artifacts as blockers. Local paths inside machine-readable diagnostic/detail artifacts are warnings because those files often preserve per-image provenance for reproducibility; they should still be reviewed before a final anonymized upload.",
        "",
        "## Summary",
        "",
        "No findings." if summary.empty else _markdown_table(summary, ["severity", "issue", "findings"]),
        "",
        "## Blockers",
        "",
        "None." if blocker_frame.empty else _markdown_table(blocker_frame, ["path", "type", "issue", "line", "example"]),
        "",
        "## Warnings",
        "",
        "None." if warning_frame.empty else _markdown_table(warning_frame, ["path", "type", "issue", "line", "example"]),
        "",
        f"Machine-readable findings: `{findings_out.relative_to(repo_root).as_posix()}`",
        "",
    ]
    text = "\n".join(lines)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    return text, findings


def main() -> None:
    args = parse_args()
    text, _findings = build_privacy_audit(
        repo_root=Path(args.repo_root),
        manifest_path=Path(args.manifest),
        out_path=Path(args.out_path),
        findings_out=Path(args.findings_out),
        run_date=date.fromisoformat(args.run_date),
    )
    print(Path(args.out_path).resolve())
    print(Path(args.findings_out).resolve())
    if not text:
        raise SystemExit("No audit report generated")


if __name__ == "__main__":
    main()
