from __future__ import annotations

import argparse
import re
from pathlib import Path

import pandas as pd


REQUIRED_COLUMNS = {"key", "title", "year", "primary_url", "theme"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build draft BibTeX references from the paper-facing literature map.")
    parser.add_argument("--literature-map", default="reports/assets/literature_map.csv")
    parser.add_argument("--out-bib", default="references.bib")
    parser.add_argument("--manifest-out", default="reports/assets/references_bib_manifest.csv")
    parser.add_argument("--report-out", default="reports/references_bib_2026_06_14.md")
    return parser.parse_args()


def _bibtex_escape(value: object) -> str:
    text = "" if value is None or pd.isna(value) else str(value)
    return text.replace("\\", r"\textbackslash{}").replace("{", r"\{").replace("}", r"\}")


def _safe_key(value: str) -> str:
    key = re.sub(r"[^A-Za-z0-9_:-]+", "_", value.strip())
    if not key:
        raise ValueError("Empty BibTeX key")
    return key


def build_bib_entries(literature_map: Path) -> tuple[str, pd.DataFrame]:
    frame = pd.read_csv(literature_map)
    missing = REQUIRED_COLUMNS - set(frame.columns)
    if missing:
        raise ValueError(f"Literature map is missing columns: {sorted(missing)}")
    if frame["key"].duplicated().any():
        duplicates = frame.loc[frame["key"].duplicated(), "key"].tolist()
        raise ValueError(f"Duplicate bibliography keys: {duplicates}")

    entries = [
        "% Auto-generated draft references from reports/assets/literature_map.csv.",
        "% Verify authors, venues, page numbers, and DOI fields before final submission.",
        "",
    ]
    rows = []
    for row in frame.sort_values(["year", "key"]).itertuples(index=False):
        key = _safe_key(str(row.key))
        title = _bibtex_escape(row.title)
        year = int(row.year)
        url = _bibtex_escape(row.primary_url)
        theme = _bibtex_escape(row.theme)
        entries.extend(
            [
                f"@misc{{{key},",
                f"  title = {{{title}}},",
                "  author = {{Authors to verify}},",
                f"  year = {{{year}}},",
                f"  url = {{{url}}},",
                f"  note = {{Draft entry generated from literature map; theme: {theme}. Verify bibliographic metadata before submission.}},",
                "}",
                "",
            ]
        )
        rows.append(
            {
                "key": key,
                "title": row.title,
                "year": year,
                "primary_url": row.primary_url,
                "theme": row.theme,
                "status": "draft_metadata_verify_before_submission",
            }
        )
    return "\n".join(entries), pd.DataFrame(rows)


def _markdown_table(frame: pd.DataFrame) -> str:
    columns = list(frame.columns)
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame.itertuples(index=False):
        lines.append("| " + " | ".join(str(value).replace("\n", " ").replace("|", "\\|") for value in row) + " |")
    return "\n".join(lines)


def write_report(manifest: pd.DataFrame, report_out: Path, out_bib: Path) -> None:
    lines = [
        "# Draft References BibTeX",
        "",
        "Run date: 2026-06-14",
        "",
        "Generated by `scripts/build_references_bib.py` from `reports/assets/literature_map.csv`.",
        "",
        "These are draft `@misc` entries intended to make the generated WIFS/DFF skeletons citeable while drafting. Verify authors, venues, page numbers, and DOI fields before submission.",
        "",
        f"Output BibTeX: `{out_bib.as_posix()}`",
        "",
        _markdown_table(manifest),
        "",
    ]
    report_out.parent.mkdir(parents=True, exist_ok=True)
    report_out.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    text, manifest = build_bib_entries(Path(args.literature_map))
    out_bib = Path(args.out_bib)
    out_bib.write_text(text, encoding="utf-8")
    manifest_out = Path(args.manifest_out)
    manifest_out.parent.mkdir(parents=True, exist_ok=True)
    manifest.to_csv(manifest_out, index=False)
    write_report(manifest, Path(args.report_out), out_bib)
    print(out_bib.resolve())
    print(manifest_out.resolve())
    print(Path(args.report_out).resolve())


if __name__ == "__main__":
    main()
