from __future__ import annotations

import argparse
import re
from pathlib import Path

import pandas as pd

from operating_mode_utils import (
    load_calibration_operating_modes,
    operating_mode_guidance_sentence,
)
from source_stress_utils import load_source_stress_summary, source_stress_sentence
from tiled_dino_tradeoff_utils import load_tiled_dino_tradeoff_summary, tiled_dino_sentence


RESULT_IDS = [
    "ishu_same_combined_v3",
    "ishu_same_resnet18",
    "ishu_same_physics_guided",
    "ishu_to_ms_clip_standalone",
    "ishu_to_ms_scp_fusion_all_foundation",
    "ishu_to_ms_triage5_clip_standalone",
    "ms_to_ishu_tuned_fusion_constraint_sweep_best",
    "ms_to_ishu_tuned_fusion_native_tiling_best",
    "ms_to_ishu_tuned_fusion_jpeg30",
    "ms_to_ishu_tuned_fusion_blur1",
    "ms_to_ishu_tuned_fusion_social_720p",
]

CONTRIBUTIONS = [
    (
        "source-heldout framing",
        "Evaluate AI-image detection as a cross-source forensic problem where ranking, calibration, fake-call rate, and triage coverage are reported separately.",
    ),
    (
        "physics/neural/foundation comparison",
        "Compare conventional physical/signal features, ResNet-18, physics-guided ResNet fusion, frozen ConvNeXt/DINOv2/CLIP, and saved-score SCP-Fusion under repeated seeds.",
    ),
    (
        "calibrated operating points",
        "Show that source-aware thresholds and strict two-threshold triage can be more defensible than a single default binary decision under generator shift.",
    ),
    (
        "robustness and failure analysis",
        "Stress the best reverse tuned-fusion operating point with JPEG, blur, resize, crop, noise, screenshot/social processing, and native-tiled physical/foundation scores.",
    ),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build venue-specific abstract and paper text drafts from checked-in result tables."
    )
    parser.add_argument(
        "--core-results",
        default="reports/assets/publication_core_results.csv",
        help="Core result table generated by build_publication_tables.py.",
    )
    parser.add_argument(
        "--claim-matrix",
        default="reports/assets/claim_evidence_matrix.csv",
        help="Claim/evidence matrix generated by build_claim_evidence_matrix.py.",
    )
    parser.add_argument(
        "--out-path",
        default="reports/submission_text_drafts_2026_06_14.md",
        help="Markdown text draft report to write.",
    )
    parser.add_argument(
        "--word-counts-out",
        default="reports/assets/submission_text_drafts_word_counts.csv",
        help="Machine-readable abstract word counts to write.",
    )
    parser.add_argument(
        "--tiled-dino-tradeoff",
        default="reports/assets/tiled_dinov2_calibration_tradeoff.csv",
        help="Tiled-DINO transform-stress tradeoff table generated by build_tiled_dinov2_calibration_tradeoff.py.",
    )
    parser.add_argument(
        "--source-stress-summary",
        default="reports/assets/ms_cocoai_to_ishu_source_holdout_model_selection_source_summary.csv",
        help="Held-out-generator stress table generated by select_reverse_fusion_by_source_holdout.py.",
    )
    parser.add_argument(
        "--calibration-operating-modes",
        default="reports/assets/calibration_operating_modes.csv",
        help="Objective-specific calibration and operating-mode selector table.",
    )
    return parser.parse_args()


def _row(core: pd.DataFrame, finding_id: str) -> pd.Series:
    matches = core[core["finding_id"] == finding_id]
    if matches.empty:
        raise ValueError(f"Missing finding_id={finding_id!r}")
    return matches.iloc[0]


def _metric(row: pd.Series, column: str) -> str:
    value = row.get(column)
    if pd.isna(value):
        return ""
    return f"{float(value):.4f}"


def _result_sentence(core: pd.DataFrame, finding_id: str) -> str:
    row = _row(core, finding_id)
    parts = []
    for column, label in [
        ("accuracy", "accuracy"),
        ("auc", "AUC"),
        ("brier", "Brier"),
        ("ece", "ECE"),
        ("predicted_fake_rate", "fake-call rate"),
        ("coverage", "coverage"),
        ("decided_accuracy", "decided-case accuracy"),
    ]:
        value = _metric(row, column)
        if value:
            parts.append(f"{label} {value}")
    metrics = " / ".join(parts)
    return f"`{finding_id}`: {row['method']} on {row['setting']} reaches {metrics}. {row['interpretation']}"


def _word_count(text: str) -> int:
    return len(re.findall(r"\b[\w'-]+\b", text))


def _dfrws_abstract(
    core: pd.DataFrame, tiled_dino: dict[str, str], source_stress: dict[str, str]
) -> str:
    same = _row(core, "ishu_same_physics_guided")
    clip = _row(core, "ishu_to_ms_clip_standalone")
    triage = _row(core, "ishu_to_ms_triage5_clip_standalone")
    tiled = _row(core, "ms_to_ishu_tuned_fusion_native_tiling_best")
    return (
        "AI-generated image detectors often look reliable on a familiar benchmark, but forensic use depends on what happens when generator source and image processing change. "
        "We present a public source-heldout evaluation of real-vs-generated image detection across physical/signal features, ResNet-18, a physics-guided ResNet fusion model, frozen ConvNeXt/DINOv2/CLIP encoders, and lightweight saved-score fusion. "
        f"On the Ishu AI-vs-real benchmark, physics-guided fusion improves the same-domain anchor to {_metric(same, 'accuracy')} accuracy and {_metric(same, 'auc')} AUC, but cross-source transfer tells a different story: frozen CLIP is the strongest standalone ranker on Ishu to source-balanced MS COCOAI at {_metric(clip, 'accuracy')} accuracy and {_metric(clip, 'auc')} AUC. "
        f"Strict source-heldout triage with CLIP decides {_metric(triage, 'coverage')} of target images at {_metric(triage, 'decided_accuracy')} decided-case accuracy, showing that partial high-confidence decisions can be more defensible than forcing every image through one threshold. "
        f"In the reverse direction, a source-capped SCP-Fusion setting improves further when the conventional branch uses native-tiled scores, reaching {_metric(tiled, 'accuracy')} accuracy and {_metric(tiled, 'auc')} AUC, while blur, harsh JPEG, and resize remain clear stressors. "
        f"The selected-policy stress table identifies `{source_stress['heldout_source_name']}` as the weakest held-out generator with {source_stress['recall']} recall and {source_stress['fake_miss_rate']} fake-miss rate. "
        f"{tiled_dino_sentence(tiled_dino)} "
        "The poster emphasizes reproducible source-shift diagnostics, calibration, triage, and failure cases rather than a production detector claim."
    )


def _wifs_abstract(
    core: pd.DataFrame, tiled_dino: dict[str, str], source_stress: dict[str, str]
) -> str:
    combined = _row(core, "ishu_same_combined_v3")
    resnet = _row(core, "ishu_same_resnet18")
    physics = _row(core, "ishu_same_physics_guided")
    clip = _row(core, "ishu_to_ms_clip_standalone")
    reverse = _row(core, "ms_to_ishu_tuned_fusion_constraint_sweep_best")
    return (
        "AI-generated image detection is commonly reported as closed-set accuracy, yet forensic deployment requires stable ranking, calibration, and operating points under generator shift. "
        "We evaluate this gap with a repeated-seed benchmark spanning conventional physical/signal features, ResNet-18, physics-guided feature fusion, frozen foundation encoders, and score-level SCP-Fusion. "
        f"On Ishu same-domain splits, `combined_v3` and ResNet-18 tie at {_metric(combined, 'accuracy')} and {_metric(resnet, 'accuracy')} accuracy, while physics-guided fusion improves to {_metric(physics, 'accuracy')} accuracy and {_metric(physics, 'auc')} AUC. "
        f"Under Ishu to source-balanced MS COCOAI transfer, frozen CLIP is the strongest standalone ranker at {_metric(clip, 'auc')} AUC, whereas fusion variants expose calibration and fake-call-rate shifts. "
        f"In the reverse direction, source-capped tuned fusion reaches {_metric(reverse, 'accuracy')} accuracy and {_metric(reverse, 'auc')} AUC with a {_metric(reverse, 'predicted_fake_rate')} target fake-call rate. "
        f"Per-generator source stress flags `{source_stress['heldout_source_name']}` as the weakest held-out generator for the capped policy, with {source_stress['recall']} recall and {source_stress['fake_miss_rate']} fake-miss rate. "
        f"A tiled-DINO probe adds a mode-specific robustness rule: `tile_max` gives {tiled_dino['tile_max_acc_delta']} accuracy and {tiled_dino['tile_max_auc_delta']} AUC average deltas, while `tile_mean` is the safer Brier/ECE diagnostic. "
        "These results support reporting AI-image forensics as a source-heldout evaluation problem with separate ranking, calibration, thresholding, and triage evidence."
    )


def _dff_abstract(
    core: pd.DataFrame, tiled_dino: dict[str, str], source_stress: dict[str, str]
) -> str:
    clip = _row(core, "ishu_to_ms_clip_standalone")
    fusion = _row(core, "ishu_to_ms_scp_fusion_all_foundation")
    triage = _row(core, "ishu_to_ms_triage5_clip_standalone")
    tiled = _row(core, "ms_to_ishu_tuned_fusion_native_tiling_best")
    jpeg = _row(core, "ms_to_ishu_tuned_fusion_jpeg30")
    blur = _row(core, "ms_to_ishu_tuned_fusion_blur1")
    return (
        "Robust detection of AI-generated images is not only a model-selection problem: detectors must survive new generator sources, real-world processing, and ambiguous operating points. "
        "We introduce SCP-Fusion as a diagnostic protocol that compares and combines single-image physical/signal features, neural image classifiers, physics-guided ResNet fusion, and frozen foundation encoders for real-vs-generated image forensics. "
        f"Across repeated source-heldout experiments, frozen CLIP remains the transfer-ranking frontier on Ishu to source-balanced MS COCOAI with {_metric(clip, 'auc')} AUC, while all-foundation SCP-Fusion reaches {_metric(fusion, 'auc')} AUC and exposes where fused scores are conservative on generated images. "
        f"Strict CLIP triage covers {_metric(triage, 'coverage')} of target images at {_metric(triage, 'decided_accuracy')} decided-case accuracy, motivating partial-decision forensic workflows. "
        f"For MS COCOAI to Ishu, source-capped tuned fusion with a native-tiled conventional branch reaches {_metric(tiled, 'accuracy')} accuracy and {_metric(tiled, 'auc')} AUC, but transform checks show important weaknesses: JPEG30 drops to {_metric(jpeg, 'accuracy')} accuracy and blur drops to {_metric(blur, 'auc')} AUC. "
        f"The capped source-holdout diagnostic identifies `{source_stress['heldout_source_name']}` as the weakest held-out generator, with {source_stress['recall']} recall and {source_stress['fake_miss_rate']} fake-miss rate. "
        f"Tiled-DINO branch replacement is useful but mode-specific: `tile_max` is the stronger operating-point diagnostic and `tile_mean` is safer for Brier/ECE. "
        "The resulting benchmark package includes source-slice diagnostics, calibration metrics, robustness transforms, and qualitative failure grids, making SCP-Fusion a reproducible framework for studying robustness and dataset bias rather than a universal best-detector claim."
    )


def _claims_to_carry(claims: pd.DataFrame) -> pd.DataFrame:
    return claims[claims["status"].isin(["ready", "ready_with_caveat"])][
        ["claim_id", "status", "submission_use", "risk_or_caveat"]
    ]


def _markdown_escape(value: object) -> str:
    if value is None or pd.isna(value):
        return ""
    return str(value).replace("\n", " ").replace("|", "\\|")


def _markdown_table(frame: pd.DataFrame, columns: list[str]) -> str:
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame[columns].itertuples(index=False):
        lines.append("| " + " | ".join(_markdown_escape(value) for value in row) + " |")
    return "\n".join(lines)


def build_submission_text(
    core_results: Path,
    claim_matrix: Path,
    tiled_dino_tradeoff: Path,
    source_stress_summary: Path,
    calibration_operating_modes: Path,
) -> tuple[str, pd.DataFrame]:
    core = pd.read_csv(core_results)
    claims = pd.read_csv(claim_matrix)
    tiled_dino = load_tiled_dino_tradeoff_summary(tiled_dino_tradeoff)
    if tiled_dino is None:
        raise ValueError("Missing tiled-DINO tradeoff summary")
    source_stress = load_source_stress_summary(source_stress_summary)
    if source_stress is None:
        raise ValueError("Missing source-stress summary")
    operating_modes = load_calibration_operating_modes(calibration_operating_modes)
    for finding_id in RESULT_IDS:
        _row(core, finding_id)

    abstracts = {
        "DFRWS poster abstract": _dfrws_abstract(core, tiled_dino, source_stress),
        "WIFS compact abstract": _wifs_abstract(core, tiled_dino, source_stress),
        "DFF workshop abstract": _dff_abstract(core, tiled_dino, source_stress),
    }
    counts = pd.DataFrame(
        [{"draft": name, "word_count": _word_count(text)} for name, text in abstracts.items()]
    )
    result_sentences = pd.DataFrame(
        {
            "finding_id": RESULT_IDS,
            "draft_sentence": [_result_sentence(core, finding_id) for finding_id in RESULT_IDS],
        }
    )
    contributions = pd.DataFrame(CONTRIBUTIONS, columns=["contribution", "wording"])
    claims_display = _claims_to_carry(claims)

    lines = [
        "# Submission Text Drafts",
        "",
        "Run date: 2026-06-14",
        "",
        "Generated by `scripts/build_submission_text_drafts.py` from `reports/assets/publication_core_results.csv` and `reports/assets/claim_evidence_matrix.csv`.",
        "",
        "These are editable authoring drafts. The wording intentionally preserves caveats: single-image physical proxy, CLIP as the current ranking frontier, SCP-Fusion as a diagnostic protocol, and native/foundation tiling as a bounded diagnostic.",
        "",
        "## Abstract Word Counts",
        "",
        _markdown_table(counts, ["draft", "word_count"]),
        "",
        "## DFRWS Poster Abstract",
        "",
        abstracts["DFRWS poster abstract"],
        "",
        "## WIFS Compact Abstract",
        "",
        abstracts["WIFS compact abstract"],
        "",
        "## DFF Workshop Abstract",
        "",
        abstracts["DFF workshop abstract"],
        "",
        "## Contribution Wording",
        "",
        _markdown_table(contributions, ["contribution", "wording"]),
        "",
        "## Tiled-DINO Mode Tradeoff",
        "",
        tiled_dino_sentence(tiled_dino),
        "",
        "Paper-safe wording: use `tile_max` for decision/ranking robustness headlines with a calibration caveat, and use `tile_mean` for Brier/ECE discussion.",
        "",
        "## Held-Out Generator Stress",
        "",
        source_stress_sentence(source_stress),
        "",
        "## Calibration Operating Mode Guidance",
        "",
        operating_mode_guidance_sentence(operating_modes),
        "",
        "## Result Sentences",
        "",
        _markdown_table(result_sentences, ["finding_id", "draft_sentence"]),
        "",
        "## Claims To Carry",
        "",
        _markdown_table(claims_display, list(claims_display.columns)),
        "",
        "## WIFS Six-Page Skeleton",
        "",
        "| section | target space | required text move |",
        "| --- | --- | --- |",
        "| Introduction | 0.75 page | Motivate source-heldout evaluation and separate ranking from decisions. |",
        "| Related work | 0.75 page | Position generated-image detectors, physical/signal forensics, foundation encoders, and calibration. |",
        "| Data and audit | 0.75 page | Describe Ishu, source-balanced MS COCOAI, source labels, splits, and leakage checks. |",
        "| Methods | 1.0 page | Define combined_v3/v4, ResNet-18, physics-guided fusion, frozen encoders, score fusion, and source thresholds. |",
        "| Results | 1.5 pages | Lead with same-domain tie, physics-guided gain, CLIP transfer frontier, reverse tuned fusion, and robustness stressors. |",
        "| Failure analysis and limitations | 0.75 page | Use qualitative grids and caveats; avoid production-detector language. |",
        "| Reproducibility | 0.25 page | Point to public repo, manifests, and command builders. |",
        "",
        "## DFF Paper Expansion Hooks",
        "",
        "- Add the combined_v4 source-slice diagnostics as dataset-bias evidence.",
        "- Use seed-17 and seed-29 failure grids as an explainability/failure-analysis spread.",
        "- Give robustness transforms a full table and keep native tiling in a bounded diagnostic paragraph.",
        "- Include calibration and triage as separate objectives, not just post-processing footnotes.",
        "",
        "## Language To Avoid",
        "",
        "- Avoid `photometric stereo` without the qualifier `single-image proxy`.",
        "- Avoid `SCP-Fusion beats CLIP`; say it exposes complementary calibration and operating-point behavior.",
        "- Avoid `robust to processing`; say which transforms were stable and which were weak.",
        "",
    ]
    return "\n".join(lines), counts


def main() -> None:
    args = parse_args()
    text, counts = build_submission_text(
        Path(args.core_results),
        Path(args.claim_matrix),
        Path(args.tiled_dino_tradeoff),
        Path(args.source_stress_summary),
        Path(args.calibration_operating_modes),
    )
    out_path = Path(args.out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    counts_path = Path(args.word_counts_out)
    counts_path.parent.mkdir(parents=True, exist_ok=True)
    counts.to_csv(counts_path, index=False)
    print(out_path.resolve())
    print(counts_path.resolve())


if __name__ == "__main__":
    main()
