from __future__ import annotations

import argparse
import importlib.util
import re
from datetime import date
from pathlib import Path
from types import ModuleType

import pandas as pd


DEFAULT_RUN_DATE = date.today()
VENUE_KEYS = {
    "DFRWS-USA 2026 poster/demo": "DFRWS",
    "IEEE WIFS 2026 paper": "WIFS",
    "DFF-2026 ACM Multimedia workshop": "DFF",
}

LINT_REPORTS = [
    {
        "name": "DFRWS poster package",
        "path": "reports/dfrws_poster_package_lint_2026_06_14.md",
        "venues": "DFRWS",
        "purpose": "Poster asset, key-number, dimension, and caution checks.",
    },
    {
        "name": "submission result tables",
        "path": "reports/submission_result_tables_lint_2026_06_14.md",
        "venues": "DFRWS,WIFS,DFF",
        "purpose": "Compact table consistency against canonical result rows.",
    },
    {
        "name": "claim evidence matrix",
        "path": "reports/claim_evidence_matrix_lint_2026_06_14.md",
        "venues": "DFRWS,WIFS,DFF",
        "purpose": "Claim IDs, artifacts, evidence IDs, caveats, and overclaim checks.",
    },
    {
        "name": "paper section drafts",
        "path": "reports/paper_section_drafts_lint_2026_06_14.md",
        "venues": "WIFS,DFF",
        "purpose": "Paper prose metric anchors, caveats, and overclaim checks.",
    },
    {
        "name": "paper skeletons",
        "path": "reports/paper_skeleton_lint_2026_06_14.md",
        "venues": "WIFS,DFF",
        "purpose": "WIFS/DFF skeleton structure, referenced assets, and guardrails.",
    },
    {
        "name": "manuscript drafts",
        "path": "reports/manuscript_drafts_lint_2026_06_14.md",
        "venues": "WIFS,DFF",
        "purpose": "Assembled manuscript draft section, asset, word-count, and guardrail checks.",
    },
    {
        "name": "submission anonymity",
        "path": "reports/submission_anonymity_audit_2026_06_15.md",
        "venues": "WIFS,DFF",
        "purpose": "Blind-review author, account, path, and public-repository wording checks.",
    },
    {
        "name": "submission package",
        "path": "reports/submission_package_lint_2026_06_14.md",
        "venues": "DFRWS,WIFS,DFF",
        "purpose": "Packet assets, abstract word counts, and abstract overclaims.",
    },
]

STATUS_PATTERN = re.compile(r"Status: \*\*(?P<status>PASS|FAIL)\*\* \((?P<passed>\d+)/(?P<total>\d+) checks passed\)")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a venue-level submission scorecard from packet, claim, and lint artifacts."
    )
    parser.add_argument("--repo-root", default=".", help="Repository root for resolving generated artifacts.")
    parser.add_argument(
        "--manifest",
        default="reports/assets/submission_packet_manifest.csv",
        help="Submission packet manifest generated by build_submission_packet.py.",
    )
    parser.add_argument(
        "--claim-matrix",
        default="reports/assets/claim_evidence_matrix.csv",
        help="Claim/evidence matrix generated by build_claim_evidence_matrix.py.",
    )
    parser.add_argument(
        "--out-path",
        default="reports/submission_scorecard_2026_06_14.md",
        help="Markdown scorecard report to write.",
    )
    parser.add_argument(
        "--summary-out",
        default="reports/assets/submission_scorecard.csv",
        help="Machine-readable venue scorecard summary to write.",
    )
    parser.add_argument(
        "--run-date",
        default=DEFAULT_RUN_DATE.isoformat(),
        help="Date used for deadline countdowns, in YYYY-MM-DD format. Defaults to today's local date.",
    )
    return parser.parse_args()


def _load_packet_builder(repo_root: Path) -> ModuleType:
    builder_path = repo_root / "scripts" / "build_submission_packet.py"
    spec = importlib.util.spec_from_file_location("submission_packet_builder", builder_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load submission packet builder from {builder_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _has_venue(venues: object, venue_key: str) -> bool:
    if pd.isna(venues):
        return False
    return venue_key in [part.strip() for part in str(venues).split(",")]


def _parse_lint_status(repo_root: Path, spec: dict[str, str]) -> dict[str, object]:
    path = repo_root / spec["path"]
    if not path.exists():
        return {
            **spec,
            "exists": False,
            "status": "MISSING",
            "passed_checks": 0,
            "total_checks": 0,
        }
    text = path.read_text(encoding="utf-8")
    match = STATUS_PATTERN.search(text)
    if not match:
        return {
            **spec,
            "exists": True,
            "status": "UNKNOWN",
            "passed_checks": 0,
            "total_checks": 0,
        }
    return {
        **spec,
        "exists": True,
        "status": match.group("status"),
        "passed_checks": int(match.group("passed")),
        "total_checks": int(match.group("total")),
    }


def _claim_counts(claims: pd.DataFrame, venue_key: str) -> dict[str, int]:
    subset = claims[claims["submission_use"].fillna("").str.contains(venue_key, case=False, regex=False)]
    return {
        "ready_claims": int((subset["status"] == "ready").sum()),
        "caveated_claims": int((subset["status"] == "ready_with_caveat").sum()),
        "needs_more_evidence_claims": int((subset["status"] == "needs_more_evidence").sum()),
    }


def _venue_artifact_counts(manifest: pd.DataFrame, venue_key: str) -> dict[str, int]:
    subset = manifest[manifest["venues"].apply(lambda value: _has_venue(value, venue_key))]
    required = subset[subset["required"].astype(bool)]
    optional_qc = subset[(~subset["required"].astype(bool)) & (subset["type"] == "quality-control")]
    return {
        "required_artifacts_present": int(required["exists"].astype(bool).sum()),
        "required_artifacts_total": int(len(required)),
        "quality_control_artifacts_present": int(optional_qc["exists"].astype(bool).sum()),
        "quality_control_artifacts_total": int(len(optional_qc)),
    }


def _venue_lint_counts(lints: pd.DataFrame, venue_key: str) -> dict[str, int | str]:
    subset = lints[lints["venues"].apply(lambda value: _has_venue(value, venue_key))]
    pass_count = int((subset["status"] == "PASS").sum())
    total = int(len(subset))
    checks_passed = int(subset["passed_checks"].sum())
    checks_total = int(subset["total_checks"].sum())
    status = "PASS" if total > 0 and pass_count == total and checks_passed == checks_total else "ATTENTION"
    return {
        "lint_reports_passed": pass_count,
        "lint_reports_total": total,
        "lint_checks_passed": checks_passed,
        "lint_checks_total": checks_total,
        "lint_status": status,
    }


def _packet_status(row: dict[str, object]) -> str:
    required_ok = row["required_artifacts_present"] == row["required_artifacts_total"]
    lint_ok = row["lint_status"] == "PASS"
    no_missing_claims = row["needs_more_evidence_claims"] == 0
    if required_ok and lint_ok and no_missing_claims:
        return "ready_to_polish"
    if required_ok and lint_ok:
        return "drafting_ready_with_claim_caveats"
    return "needs_attention"


def build_scorecard(
    repo_root: Path,
    manifest_path: Path,
    claim_matrix_path: Path,
    run_date: date = DEFAULT_RUN_DATE,
) -> tuple[str, pd.DataFrame, pd.DataFrame]:
    repo_root = repo_root.resolve()
    packet_builder = _load_packet_builder(repo_root)
    manifest = pd.read_csv(manifest_path)
    claims = pd.read_csv(claim_matrix_path)
    lints = pd.DataFrame([_parse_lint_status(repo_root, spec) for spec in LINT_REPORTS])

    rows = []
    for venue in packet_builder.VENUES:
        venue_key = VENUE_KEYS[venue["venue"]]
        row: dict[str, object] = {
            "venue": venue["venue"],
            "venue_key": venue_key,
            "deadline": venue["deadline"],
            "days_until_deadline": (date.fromisoformat(venue["deadline"]) - run_date).days,
            "current_status": venue["status"],
            "title": venue["title"],
            "next_action": venue["next_action"],
        }
        row.update(_venue_artifact_counts(manifest, venue_key))
        row.update(_venue_lint_counts(lints, venue_key))
        row.update(_claim_counts(claims, venue_key))
        row["packet_status"] = _packet_status(row)
        rows.append(row)

    scorecard = pd.DataFrame(rows)
    text = _scorecard_markdown(scorecard, lints, run_date)
    return text, scorecard, lints


def _format_ratio(row: pd.Series, numerator: str, denominator: str) -> str:
    return f"{int(row[numerator])}/{int(row[denominator])}"


def _markdown_escape(value: object) -> str:
    if value is None or pd.isna(value):
        return ""
    return str(value).replace("\n", " ").replace("|", "\\|")


def _markdown_table(frame: pd.DataFrame, columns: list[str]) -> str:
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame[columns].itertuples(index=False):
        lines.append("| " + " | ".join(_markdown_escape(value) for value in row) + " |")
    return "\n".join(lines)


def _scorecard_markdown(scorecard: pd.DataFrame, lints: pd.DataFrame, run_date: date) -> str:
    display = pd.DataFrame(
        {
            "venue": scorecard["venue"],
            "deadline": scorecard["deadline"],
            "days_left": scorecard["days_until_deadline"],
            "packet_status": scorecard["packet_status"],
            "artifacts": [
                _format_ratio(row, "required_artifacts_present", "required_artifacts_total")
                for _index, row in scorecard.iterrows()
            ],
            "lint_reports": [
                _format_ratio(row, "lint_reports_passed", "lint_reports_total")
                for _index, row in scorecard.iterrows()
            ],
            "lint_checks": [
                _format_ratio(row, "lint_checks_passed", "lint_checks_total")
                for _index, row in scorecard.iterrows()
            ],
            "claims": [
                (
                    f"ready {int(row.ready_claims)}, caveated {int(row.caveated_claims)}, "
                    f"needs {int(row.needs_more_evidence_claims)}"
                )
                for row in scorecard.itertuples(index=False)
            ],
            "next_action": scorecard["next_action"],
        }
    )
    lint_display = lints[
        ["name", "venues", "status", "passed_checks", "total_checks", "path", "purpose"]
    ].copy()
    lines = [
        "# Submission Scorecard",
        "",
        f"Run date: {run_date.isoformat()}",
        "",
        "Generated by `scripts/build_submission_scorecard.py` from the submission packet manifest, claim-evidence matrix, and quality-control reports.",
        "",
        "This scorecard is deliberately conservative: `ready_to_polish` means the checked-in packet is internally consistent, not that the final venue upload is complete.",
        "",
        "## Venue Summary",
        "",
        _markdown_table(display, list(display.columns)),
        "",
        "## Quality-Control Reports",
        "",
        _markdown_table(lint_display, list(lint_display.columns)),
        "",
        "## Reading The Status",
        "",
        "- `ready_to_polish`: required artifacts exist, relevant lint reports pass, and venue-linked claims do not require more evidence.",
        "- `drafting_ready_with_claim_caveats`: artifacts and lints pass, but at least one venue-linked claim still needs explicit caveat handling.",
        "- `needs_attention`: an artifact or quality-control report is missing or failing.",
        "",
        "## Current Editorial Guardrails",
        "",
        "- DFRWS can lead with source-heldout diagnostics and CLIP triage, but still needs final poster export/polish.",
        "- WIFS should keep the paper compact: ranking, calibration, fake-call rate, and source-aware decisions are the core story.",
        "- DFF can carry the broader SCP-Fusion diagnostic-protocol framing, with failure grids and source-slice diagnostics as the richer workshop material.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    text, scorecard, _lints = build_scorecard(
        repo_root=Path(args.repo_root),
        manifest_path=Path(args.manifest),
        claim_matrix_path=Path(args.claim_matrix),
        run_date=date.fromisoformat(args.run_date),
    )
    out_path = Path(args.out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    summary_path = Path(args.summary_out)
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    scorecard.to_csv(summary_path, index=False)
    print(out_path.resolve())
    print(summary_path.resolve())


if __name__ == "__main__":
    main()
