from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import pandas as pd

from source_stress_utils import DEFAULT_SOURCE_STRESS_POLICY, source_stress_sentence


INK = "#17212B"
GRID = "#D8DEE6"
PANEL = "#F8FAFC"
UTILITY = "#2E6F95"
MISS = "#D07C2C"
WEAK = "#C94C4C"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a held-out-generator stress figure from source-holdout selection folds."
    )
    parser.add_argument(
        "--source-summary",
        default="reports/assets/ms_cocoai_to_ishu_source_holdout_model_selection_source_summary.csv",
        help="Policy-by-heldout-generator summary generated by select_reverse_fusion_by_source_holdout.py.",
    )
    parser.add_argument("--policy", default=DEFAULT_SOURCE_STRESS_POLICY)
    parser.add_argument("--out-dir", default="reports/assets")
    parser.add_argument(
        "--report-out",
        default="reports/source_holdout_generator_stress_2026_06_14.md",
    )
    parser.add_argument("--dpi", type=int, default=220)
    return parser.parse_args()


def source_stress_frame(source_summary: Path, policy: str) -> pd.DataFrame:
    frame = pd.read_csv(source_summary)
    required = {
        "selection_policy",
        "heldout_source_name",
        "source_holdout_utility_mean",
        "source_holdout_recall_mean",
        "source_holdout_fake_miss_rate_mean",
        "source_holdout_predicted_positive_rate_mean",
    }
    missing = required - set(frame.columns)
    if missing:
        raise ValueError(f"{source_summary} is missing columns: {sorted(missing)}")
    policy_frame = frame[frame["selection_policy"].astype(str) == policy].copy()
    if policy_frame.empty:
        raise ValueError(f"No rows found for selection_policy={policy!r}")
    policy_frame = policy_frame.sort_values(
        ["source_holdout_utility_mean", "source_holdout_fake_miss_rate_mean"],
        ascending=[True, False],
    )
    return policy_frame[
        [
            "selection_policy",
            "heldout_source_name",
            "source_holdout_utility_mean",
            "source_holdout_recall_mean",
            "source_holdout_fake_miss_rate_mean",
            "source_holdout_predicted_positive_rate_mean",
        ]
    ].reset_index(drop=True)


def _summary_from_frame(frame: pd.DataFrame) -> dict[str, str]:
    weakest = frame.iloc[0]
    return {
        "policy": str(weakest["selection_policy"]),
        "heldout_source_name": str(weakest["heldout_source_name"]),
        "utility": f"{float(weakest['source_holdout_utility_mean']):.4f}",
        "recall": f"{float(weakest['source_holdout_recall_mean']):.4f}",
        "fake_miss_rate": f"{float(weakest['source_holdout_fake_miss_rate_mean']):.4f}",
    }


def _style_axis(ax: plt.Axes) -> None:
    ax.set_facecolor(PANEL)
    ax.grid(axis="x", color=GRID, linewidth=0.8)
    ax.set_axisbelow(True)
    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.tick_params(axis="both", colors=INK, labelsize=11)


def _save_both(fig: plt.Figure, stem: Path, dpi: int) -> tuple[Path, Path]:
    png = stem.with_suffix(".png")
    svg = stem.with_suffix(".svg")
    fig.savefig(png, dpi=dpi, bbox_inches="tight", facecolor="white")
    fig.savefig(svg, bbox_inches="tight", facecolor="white", metadata={"Date": "2026-06-14"})
    svg.write_text(
        "\n".join(line.rstrip() for line in svg.read_text(encoding="utf-8").splitlines()) + "\n",
        encoding="utf-8",
    )
    plt.close(fig)
    return png, svg


def build_figure(frame: pd.DataFrame, out_dir: Path, dpi: int) -> tuple[Path, Path]:
    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "svg.fonttype": "none",
            "svg.hashsalt": "ai-image-forensics-source-stress",
            "axes.titleweight": "bold",
        }
    )
    display = frame.copy()
    display["source_label"] = display["heldout_source_name"].astype(str)
    y = list(range(len(display)))
    bar_colors = [WEAK] + [UTILITY] * (len(display) - 1)

    fig, axes = plt.subplots(1, 2, figsize=(14.0, 6.2), constrained_layout=True)
    fig.suptitle(
        "Held-out generator stress under capped source-holdout selection",
        fontsize=17,
        color=INK,
        fontweight="bold",
    )

    ax = axes[0]
    _style_axis(ax)
    utilities = display["source_holdout_utility_mean"].astype(float)
    ax.barh(y, utilities, color=bar_colors)
    ax.set_yticks(y)
    ax.set_yticklabels(display["source_label"])
    ax.invert_yaxis()
    ax.set_xlabel("mean source-holdout utility", color=INK)
    ax.set_title("Lower utility = harder held-out source", loc="left", color=INK, pad=12)
    ax.set_xlim(0.0, max(2.05, float(utilities.max()) + 0.1))
    for pos, value in zip(y, utilities, strict=True):
        ax.text(float(value) + 0.03, pos, f"{float(value):.3f}", va="center", fontsize=10, color=INK)

    ax = axes[1]
    _style_axis(ax)
    recall = display["source_holdout_recall_mean"].astype(float)
    miss = display["source_holdout_fake_miss_rate_mean"].astype(float)
    ax.barh([pos - 0.18 for pos in y], recall, height=0.32, color=UTILITY, label="Recall")
    ax.barh([pos + 0.18 for pos in y], miss, height=0.32, color=MISS, label="Fake-miss rate")
    ax.set_yticks(y)
    ax.set_yticklabels(display["source_label"])
    ax.invert_yaxis()
    ax.set_xlim(0.0, 1.05)
    ax.set_xlabel("fraction", color=INK)
    ax.set_title("Recall/fake-miss split", loc="left", color=INK, pad=12)
    for pos, value in zip(y, recall, strict=True):
        ax.text(float(value) + 0.015, pos - 0.18, f"{float(value):.3f}", va="center", fontsize=9, color=INK)
    for pos, value in zip(y, miss, strict=True):
        ax.text(float(value) + 0.015, pos + 0.18, f"{float(value):.3f}", va="center", fontsize=9, color=INK)
    ax.legend(frameon=False, loc="lower right", fontsize=10)

    return _save_both(fig, out_dir / "source_holdout_generator_stress", dpi)


def _markdown_table(frame: pd.DataFrame) -> str:
    display = frame.copy()
    for column in [
        "source_holdout_utility_mean",
        "source_holdout_recall_mean",
        "source_holdout_fake_miss_rate_mean",
        "source_holdout_predicted_positive_rate_mean",
    ]:
        display[column] = display[column].map(lambda value: f"{float(value):.4f}")
    columns = list(display.columns)
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in display.itertuples(index=False):
        lines.append("| " + " | ".join(str(value).replace("\n", " ") for value in row) + " |")
    return "\n".join(lines)


def write_report(frame: pd.DataFrame, png_path: Path, svg_path: Path, report_out: Path) -> None:
    summary = _summary_from_frame(frame)
    try:
        png_ref = png_path.relative_to(report_out.parent).as_posix()
    except ValueError:
        png_ref = png_path.as_posix()
    lines = [
        "# Source-Holdout Generator Stress Figure",
        "",
        "Run date: 2026-06-14",
        "",
        "Generated by `scripts/build_source_stress_figure.py` from the selected source-holdout policy summary.",
        "",
        source_stress_sentence(summary),
        "",
        f"![Held-out generator stress]({png_ref})",
        "",
        "## Source Stress Table",
        "",
        _markdown_table(frame),
        "",
        "## Files",
        "",
        "| asset | path |",
        "| --- | --- |",
        f"| PNG | `{png_path.as_posix()}` |",
        f"| SVG | `{svg_path.as_posix()}` |",
        "| CSV | `reports/assets/source_holdout_generator_stress.csv` |",
        "",
    ]
    report_out.parent.mkdir(parents=True, exist_ok=True)
    report_out.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    frame = source_stress_frame(Path(args.source_summary), args.policy)
    csv_path = out_dir / "source_holdout_generator_stress.csv"
    frame.to_csv(csv_path, index=False)
    png_path, svg_path = build_figure(frame, out_dir, args.dpi)
    report_out = Path(args.report_out)
    write_report(frame, png_path, svg_path, report_out)
    print(csv_path.resolve())
    print(png_path.resolve())
    print(svg_path.resolve())
    print(report_out.resolve())


if __name__ == "__main__":
    main()
