from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


KEY_FINDINGS = [
    "ishu_same_combined_v3",
    "ishu_same_resnet18",
    "ishu_same_physics_guided",
    "ishu_to_ms_clip_standalone",
    "ishu_to_ms_scp_fusion_all_foundation",
    "ishu_to_ms_triage5_clip_standalone",
    "ms_to_ishu_branch_dropout_auc",
    "ms_to_ishu_tuned_fusion_constraint_sweep_best",
]

ROBUSTNESS_FINDINGS = [
    "ms_to_ishu_tuned_fusion_jpeg70",
    "ms_to_ishu_tuned_fusion_jpeg50",
    "ms_to_ishu_tuned_fusion_jpeg30",
    "ms_to_ishu_tuned_fusion_blur1",
    "ms_to_ishu_tuned_fusion_resize_half",
    "ms_to_ishu_tuned_fusion_crop85",
    "ms_to_ishu_tuned_fusion_noise3",
    "ms_to_ishu_tuned_fusion_screenshot",
    "ms_to_ishu_tuned_fusion_social_square",
]

FIGURE_PACKAGE = [
    (
        "Main transfer result",
        "reports/assets/publication_score_fusion_clip_frontier.png",
        "CLIP sets the current transfer-ranking and triage frontier.",
    ),
    (
        "Calibration and triage",
        "reports/assets/publication_triage_operating_points.png",
        "High-confidence triage is more defensible than forcing every image into a binary decision.",
    ),
    (
        "Reverse transfer",
        "reports/assets/publication_reverse_operating_points.png",
        "Source-aware operating points improve binary decisions under generator shift.",
    ),
    (
        "Robustness stress panel",
        "reports/assets/publication_reverse_transform_robustness.png",
        "Target transforms separate ranking robustness from fake-call-rate stability.",
    ),
    (
        "Failure cases",
        "reports/assets/qualitative_seed17_scp_fusion_false_negatives.png",
        "Qualitative misses and branch disagreements for forensic discussion.",
    ),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a DFRWS-facing poster brief from checked-in result tables."
    )
    parser.add_argument(
        "--core-results",
        default="reports/assets/publication_core_results.csv",
        help="Publication core result table generated by build_publication_tables.py.",
    )
    parser.add_argument(
        "--claim-matrix",
        default="reports/assets/claim_evidence_matrix.csv",
        help="Claim/evidence matrix generated by build_claim_evidence_matrix.py.",
    )
    parser.add_argument(
        "--out-path",
        default="reports/dfrws_poster_brief_2026_06_13.md",
        help="Markdown poster brief to write.",
    )
    parser.add_argument(
        "--key-numbers-out",
        default="reports/assets/dfrws_poster_key_numbers.csv",
        help="Compact CSV of poster-leading result rows.",
    )
    return parser.parse_args()


def _format_number(value: object) -> str:
    if value is None or pd.isna(value):
        return ""
    return f"{float(value):.4f}"


def _metric_summary(row: pd.Series) -> str:
    parts = []
    for column, label in [
        ("accuracy", "accuracy"),
        ("auc", "AUC"),
        ("brier", "Brier"),
        ("ece", "ECE"),
        ("predicted_fake_rate", "fake-call rate"),
        ("coverage", "coverage"),
        ("decided_accuracy", "decided accuracy"),
    ]:
        value = row.get(column)
        if pd.notna(value):
            parts.append(f"{label} {_format_number(value)}")
    return " / ".join(parts)


def _rows_by_id(frame: pd.DataFrame, finding_ids: list[str]) -> pd.DataFrame:
    rows = []
    for finding_id in finding_ids:
        matches = frame[frame["finding_id"] == finding_id]
        if matches.empty:
            raise ValueError(f"Missing finding_id={finding_id!r}")
        rows.append(matches.iloc[0])
    return pd.DataFrame(rows)


def _markdown_table(frame: pd.DataFrame, columns: list[str]) -> str:
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame.itertuples(index=False):
        values = [str(value).replace("\n", " ") for value in row]
        lines.append("| " + " | ".join(values) + " |")
    return "\n".join(lines)


def _display_rows(rows: pd.DataFrame) -> pd.DataFrame:
    return pd.DataFrame(
        {
            "finding": rows["finding_id"],
            "method": rows["method"],
            "setting": rows["setting"],
            "metrics": [_metric_summary(row) for _index, row in rows.iterrows()],
            "poster_use": rows["interpretation"],
        }
    )


def _ready_claims(claims: pd.DataFrame) -> pd.DataFrame:
    display = claims[claims["status"].isin(["ready", "ready_with_caveat"])].copy()
    display = display[
        [
            "claim_id",
            "status",
            "submission_use",
            "risk_or_caveat",
        ]
    ]
    return display


def build_poster_brief(core_results: Path, claim_matrix: Path) -> tuple[str, pd.DataFrame]:
    core = pd.read_csv(core_results)
    claims = pd.read_csv(claim_matrix)
    key_rows = _rows_by_id(core, KEY_FINDINGS)
    robustness_rows = _rows_by_id(core, ROBUSTNESS_FINDINGS)
    key_display = _display_rows(key_rows)
    robustness_display = _display_rows(robustness_rows)
    claims_display = _ready_claims(claims)

    lines = [
        "# DFRWS-USA 2026 Poster Brief",
        "",
        "Generated by `scripts/build_dfrws_poster_brief.py` from checked-in result tables.",
        "",
        "## Working Title",
        "",
        "When AI Image Detectors Travel: Source-Heldout Diagnostics for Physical, Neural, and Frozen-Encoder Forensics",
        "",
        "## One-Sentence Claim",
        "",
        (
            "AI-image forensic detectors need source-heldout evaluation because ranking, probability "
            "calibration, fake-call rate, and high-confidence triage can disagree sharply when generator "
            "source or image processing changes."
        ),
        "",
        "## Poster Spine",
        "",
        "1. Same-domain accuracy is only the warm-up: `combined_v3` and ResNet-18 tie on Ishu, while physics-guided fusion improves the in-domain anchor.",
        "2. Transfer ranking has a different winner: frozen CLIP is the strongest standalone cross-domain ranker and triage branch.",
        "3. SCP-Fusion is most useful as a diagnostic protocol: it exposes calibration, fake-call-rate, and transform-specific failure modes rather than simply replacing the best branch.",
        "4. Source-aware thresholds and triage produce more defensible forensic decisions than one default threshold everywhere.",
        "",
        "## Key Numbers",
        "",
        _markdown_table(key_display, list(key_display.columns)),
        "",
        "## Robustness Stress Panel",
        "",
        _markdown_table(robustness_display, list(robustness_display.columns)),
        "",
        "## Figure Package",
        "",
        _markdown_table(
            pd.DataFrame(FIGURE_PACKAGE, columns=["panel", "file", "poster_use"]),
            ["panel", "file", "poster_use"],
        ),
        "",
        "## Claims To Carry",
        "",
        _markdown_table(claims_display, list(claims_display.columns)),
        "",
        "## Do Not Overclaim",
        "",
        "- Do not claim SCP-Fusion beats frozen CLIP as a transfer ranker; the current evidence says CLIP is the ranking frontier.",
        "- Do not describe the photometric branch as true multi-light photometric stereo; it is a single-image physical/signal proxy.",
        "- Do not frame the tuned-fusion cap as production-ready; JPEG30, blur, resize, and screenshot transforms still expose weaknesses.",
        "",
        "## Immediate Poster TODOs",
        "",
        "- Convert this brief into a one-page visual poster or slide.",
        "- Add one compact qualitative failure grid near the robustness panel.",
        "- Keep DFRWS as a reproducibility/demo poster; reserve stronger novelty claims for WIFS/DFF after the next breadth check.",
        "",
    ]
    return "\n".join(lines), pd.concat([key_display, robustness_display], ignore_index=True)


def main() -> None:
    args = parse_args()
    text, key_numbers = build_poster_brief(Path(args.core_results), Path(args.claim_matrix))
    out_path = Path(args.out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    key_numbers_path = Path(args.key_numbers_out)
    key_numbers_path.parent.mkdir(parents=True, exist_ok=True)
    key_numbers.to_csv(key_numbers_path, index=False)
    print(out_path.resolve())
    print(key_numbers_path.resolve())


if __name__ == "__main__":
    main()
