from __future__ import annotations

import argparse
import re
from pathlib import Path

import pandas as pd


RUN_DATE = "2026-06-14"

TITLES = {
    "WIFS": "Source-Heldout Evaluation of Physical, Neural, and Frozen-Encoder Signals for AI-Generated Image Detection",
    "DFF": "SCP-Fusion: Source-Calibrated Physical and Foundation Features for Robust AI-Generated Image Forensics",
}

OUTPUTS = {
    "WIFS": "reports/wifs_manuscript_draft_2026_06_14.md",
    "DFF": "reports/dff_manuscript_draft_2026_06_14.md",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Assemble WIFS and DFF markdown manuscript drafts from generated prose and assembly maps."
    )
    parser.add_argument(
        "--assembly-map",
        default="reports/assets/manuscript_assembly_map.csv",
        help="Machine-readable assembly map generated by build_manuscript_assembly_map.py.",
    )
    parser.add_argument(
        "--section-drafts",
        default="reports/paper_section_drafts_2026_06_14.md",
        help="Generated WIFS/DFF section prose drafts.",
    )
    parser.add_argument(
        "--submission-text",
        default="reports/submission_text_drafts_2026_06_14.md",
        help="Generated submission abstracts and result sentences.",
    )
    parser.add_argument(
        "--manifest-out",
        default="reports/assets/manuscript_draft_manifest.csv",
        help="Machine-readable draft manifest to write.",
    )
    parser.add_argument(
        "--wifs-out",
        default=OUTPUTS["WIFS"],
        help="WIFS markdown draft output path.",
    )
    parser.add_argument(
        "--dff-out",
        default=OUTPUTS["DFF"],
        help="DFF markdown draft output path.",
    )
    return parser.parse_args()


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", value.lower()).strip()


def _word_count(text: str) -> int:
    return len(re.findall(r"\b[\w.-]+\b", text))


def _extract_h2_sections(text: str) -> dict[str, str]:
    matches = list(re.finditer(r"^##\s+(.+?)\s*$", text, flags=re.MULTILINE))
    sections: dict[str, str] = {}
    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        title = match.group(1).strip()
        body = text[start:end].strip()
        sections[_slug(title)] = body
    return sections


def _source_text(
    source_name: str,
    section_sources: dict[str, str],
    submission_sources: dict[str, str],
) -> str:
    key = _slug(source_name)
    if key in section_sources:
        return section_sources[key]
    if key in submission_sources:
        return submission_sources[key]
    return f"TODO: source prose for `{source_name}` was not found."


def _asset_lines(primary_assets: str) -> list[str]:
    lines = []
    for asset in [part.strip() for part in primary_assets.split(";") if part.strip()]:
        if asset.endswith((".png", ".jpg", ".jpeg")):
            lines.append(f"- Figure candidate: `{asset}`")
        elif asset.endswith(".tex"):
            lines.append(f"- Table fragment: `{asset}`")
        else:
            lines.append(f"- Supporting artifact: `{asset}`")
    return lines


def _section_heading(row: pd.Series) -> str:
    section = str(row["section"])
    if "abstract" in section.lower():
        return "Abstract"
    return section


def _section_body(
    row: pd.Series,
    section_sources: dict[str, str],
    submission_sources: dict[str, str],
) -> str:
    source_names = [part.strip() for part in str(row["source_sections"]).split(";") if part.strip()]
    body_parts = [
        _source_text(source_name, section_sources, submission_sources)
        for source_name in source_names
    ]
    body = "\n\n".join(body_parts)
    assets = "\n".join(_asset_lines(str(row["primary_assets"])))
    action = str(row["writing_action"])
    return "\n\n".join(
        [
            body,
            "**Draft assembly note:** " + action,
            "**Assets to place or cite:**\n" + assets,
        ]
    )


def _build_draft(
    venue: str,
    assembly: pd.DataFrame,
    section_sources: dict[str, str],
    submission_sources: dict[str, str],
) -> tuple[str, dict[str, object]]:
    rows = assembly[assembly["venue"] == venue].sort_values("order")
    lines = [
        f"# {TITLES[venue]}",
        "",
        f"Run date: {RUN_DATE}",
        "",
        "Generated manuscript draft assembled from generated section drafts, abstract text, and the manuscript assembly map.",
        "Author editing is still required before copying into the official venue template.",
        "",
    ]
    body_word_count = 0
    asset_count = 0
    for _index, row in rows.iterrows():
        heading = _section_heading(row)
        body = _section_body(row, section_sources, submission_sources)
        asset_count += len(_asset_lines(str(row["primary_assets"])))
        body_word_count += _word_count(body)
        lines.extend([f"## {heading}", "", body, ""])
    lines.extend(
        [
            "## Author Checklist",
            "",
            "- Replace this markdown with the official venue template before submission.",
            "- Verify bibliography metadata and image permissions.",
            "- Keep all claims tied to the claim-evidence matrix and linted result tables.",
            "- Preserve the single-image physical-proxy and no-SOTA guardrails.",
            "",
        ]
    )
    text = "\n".join(lines)
    manifest = {
        "venue": venue,
        "path": OUTPUTS[venue],
        "sections": len(rows),
        "target_pages": rows["target_pages"].sum(),
        "source_word_count": rows["source_word_count"].sum(),
        "draft_word_count": _word_count(text),
        "asset_callouts": asset_count,
    }
    return text, manifest


def build_manuscript_drafts(
    assembly_map: Path,
    section_drafts: Path,
    submission_text: Path,
) -> tuple[dict[str, str], pd.DataFrame]:
    assembly = pd.read_csv(assembly_map)
    section_sources = _extract_h2_sections(section_drafts.read_text(encoding="utf-8"))
    submission_sources = _extract_h2_sections(submission_text.read_text(encoding="utf-8"))
    outputs: dict[str, str] = {}
    manifests = []
    for venue in ["WIFS", "DFF"]:
        text, manifest = _build_draft(venue, assembly, section_sources, submission_sources)
        outputs[venue] = text
        manifests.append(manifest)
    return outputs, pd.DataFrame(manifests)


def main() -> None:
    args = parse_args()
    outputs, manifest = build_manuscript_drafts(
        Path(args.assembly_map),
        Path(args.section_drafts),
        Path(args.submission_text),
    )
    output_paths = {"WIFS": Path(args.wifs_out), "DFF": Path(args.dff_out)}
    for venue, text in outputs.items():
        out_path = output_paths[venue]
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text, encoding="utf-8")
        print(out_path.resolve())

    manifest_out = Path(args.manifest_out)
    manifest_out.parent.mkdir(parents=True, exist_ok=True)
    manifest["path"] = manifest["venue"].map(lambda venue: output_paths[str(venue)].as_posix())
    manifest.to_csv(manifest_out, index=False)
    print(manifest_out.resolve())


if __name__ == "__main__":
    main()
