from __future__ import annotations

import argparse
import re
from pathlib import Path

import pandas as pd


RUN_DATE = "2026-06-14"

ALLOWED_STATUSES = {"ready", "ready_with_caveat", "needs_more_evidence"}
ARTIFACT_BACKED_PREFIXES = {
    "calibration_operating_modes",
    "reconstruction_v2_probe",
    "tiled_dinov2_calibration_tradeoff",
}
FORBIDDEN_CLAIM_PATTERNS = [
    r"\bstate[- ]of[- ]the[- ]art\b",
    r"\bproduction[- ]ready\b",
    r"\bguaranteed\b",
    r"\buniversally beats\b",
    r"\bbeats CLIP\b",
    r"\bofficial NTIRE\b",
    r"\bofficial ImageCLEF\b",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Lint the claim/evidence matrix for resolvable evidence, caveats, and overclaim language."
    )
    parser.add_argument("--repo-root", default=".", help="Repository root for resolving artifact paths.")
    parser.add_argument(
        "--claim-matrix",
        default="reports/assets/claim_evidence_matrix.csv",
        help="Claim/evidence matrix generated by build_claim_evidence_matrix.py.",
    )
    parser.add_argument(
        "--core-results",
        default="reports/assets/publication_core_results.csv",
        help="Canonical result table containing finding_id rows.",
    )
    parser.add_argument(
        "--out-path",
        default="reports/claim_evidence_matrix_lint_2026_06_14.md",
        help="Markdown lint report to write.",
    )
    parser.add_argument(
        "--checks-out",
        default="reports/assets/claim_evidence_matrix_lint.csv",
        help="Machine-readable lint checks to write.",
    )
    return parser.parse_args()


def _add_check(rows: list[dict[str, object]], check: str, passed: bool, detail: str) -> None:
    rows.append({"check": check, "passed": bool(passed), "detail": detail})


def _split_evidence_ids(value: object) -> list[str]:
    if pd.isna(value):
        return []
    return [part.strip() for part in str(value).split(",") if part.strip()]


def _is_artifact_backed_summary(summary: object) -> bool:
    if pd.isna(summary):
        return False
    text = str(summary)
    return any(text.startswith(prefix) for prefix in ARTIFACT_BACKED_PREFIXES)


def lint_claim_evidence_matrix(
    repo_root: Path,
    claim_matrix_path: Path,
    core_results_path: Path,
) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    repo_root = repo_root.resolve()
    claims = pd.read_csv(claim_matrix_path)
    core = pd.read_csv(core_results_path)
    core_ids = set(core["finding_id"].dropna().astype(str))

    _add_check(
        rows,
        "claim IDs are unique",
        claims["claim_id"].is_unique,
        f"{claims['claim_id'].nunique()} unique claim IDs across {len(claims)} rows",
    )

    bad_status = sorted(set(claims["status"]) - ALLOWED_STATUSES)
    _add_check(
        rows,
        "claim statuses are allowed",
        not bad_status,
        "all statuses allowed" if not bad_status else ", ".join(bad_status),
    )

    missing_artifacts = []
    for claim in claims.itertuples(index=False):
        artifact = getattr(claim, "primary_artifact")
        if not isinstance(artifact, str) or not artifact.strip() or not (repo_root / artifact).exists():
            missing_artifacts.append(str(getattr(claim, "claim_id")))
    _add_check(
        rows,
        "primary artifacts exist",
        not missing_artifacts,
        "all primary artifacts exist" if not missing_artifacts else ", ".join(missing_artifacts),
    )

    missing_caveats = [
        str(claim.claim_id)
        for claim in claims.itertuples(index=False)
        if claim.status == "ready_with_caveat" and not str(claim.risk_or_caveat).strip()
    ]
    _add_check(
        rows,
        "caveated claims include caveats",
        not missing_caveats,
        "all caveated claims explain their caveat" if not missing_caveats else ", ".join(missing_caveats),
    )

    unresolved_ids = []
    artifact_backed_without_prefix = []
    for claim in claims.itertuples(index=False):
        evidence_ids = _split_evidence_ids(getattr(claim, "evidence_finding_ids"))
        if evidence_ids:
            for finding_id in evidence_ids:
                if finding_id not in core_ids:
                    unresolved_ids.append(f"{claim.claim_id}:{finding_id}")
        elif not _is_artifact_backed_summary(getattr(claim, "evidence_summary")):
            artifact_backed_without_prefix.append(str(claim.claim_id))
    _add_check(
        rows,
        "evidence IDs resolve or artifact-backed summaries are named",
        not unresolved_ids and not artifact_backed_without_prefix,
        "all evidence resolves"
        if not unresolved_ids and not artifact_backed_without_prefix
        else "; ".join(unresolved_ids + artifact_backed_without_prefix),
    )

    claim_blob = "\n".join(claims["claim"].fillna("").astype(str).tolist())
    for pattern in FORBIDDEN_CLAIM_PATTERNS:
        found = re.search(pattern, claim_blob, flags=re.IGNORECASE) is not None
        _add_check(
            rows,
            f"claim text avoids overclaim: {pattern}",
            not found,
            "not found" if not found else "found in claim text",
        )

    return pd.DataFrame(rows)


def _markdown_table(frame: pd.DataFrame) -> str:
    columns = list(frame.columns)
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame.itertuples(index=False):
        lines.append("| " + " | ".join(str(value).replace("\n", " ").replace("|", "\\|") for value in row) + " |")
    return "\n".join(lines)


def write_report(frame: pd.DataFrame, out_path: Path) -> None:
    passed = int(frame["passed"].sum())
    total = len(frame)
    status = "PASS" if passed == total else "FAIL"
    lines = [
        "# Claim Evidence Matrix Lint",
        "",
        f"Run date: {RUN_DATE}",
        "",
        f"Status: **{status}** ({passed}/{total} checks passed).",
        "",
        "Generated by `scripts/lint_claim_evidence_matrix.py` from the claim matrix and canonical result table.",
        "",
        _markdown_table(frame),
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    frame = lint_claim_evidence_matrix(
        Path(args.repo_root),
        Path(args.claim_matrix),
        Path(args.core_results),
    )
    checks_out = Path(args.checks_out)
    checks_out.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(checks_out, index=False)
    write_report(frame, Path(args.out_path))
    if not bool(frame["passed"].all()):
        failed = frame[~frame["passed"]]
        raise SystemExit(
            "Claim evidence matrix lint failed: "
            + "; ".join(f"{row.check} ({row.detail})" for row in failed.itertuples(index=False))
        )
    print(Path(args.out_path).resolve())
    print(checks_out.resolve())


if __name__ == "__main__":
    main()
