from __future__ import annotations

import argparse
import re
from pathlib import Path

import pandas as pd


ABSTRACT_HEADERS = [
    "DFRWS Poster Abstract",
    "WIFS Compact Abstract",
    "DFF Workshop Abstract",
]

ABSTRACT_TO_DRAFT = {
    "DFRWS Poster Abstract": "DFRWS poster abstract",
    "WIFS Compact Abstract": "WIFS compact abstract",
    "DFF Workshop Abstract": "DFF workshop abstract",
}

REQUIRED_GUARDRAILS = [
    "single-image physical proxy",
    "CLIP as the current ranking frontier",
    "SCP-Fusion as a diagnostic protocol",
    "native/foundation tiling as a bounded diagnostic",
]

REQUIRED_RESULT_IDS = [
    "ishu_same_physics_guided",
    "ishu_to_ms_clip_standalone",
    "ishu_to_ms_triage5_clip_standalone",
    "ms_to_ishu_tuned_fusion_constraint_sweep_best",
    "ms_to_ishu_tuned_fusion_native_tiling_best",
    "ms_to_ishu_tuned_fusion_jpeg30",
    "ms_to_ishu_tuned_fusion_blur1",
]

FORBIDDEN_ABSTRACT_PATTERNS = [
    r"\bstate[- ]of[- ]the[- ]art\b",
    r"\bproduction[- ]ready\b",
    r"\buniversally beats\b",
    r"\bbeats CLIP\b",
    r"\bphotometric stereo\b",
    r"\brobust to processing\b",
]

WORD_LIMITS = {
    "DFRWS poster abstract": (80, 500),
    "WIFS compact abstract": (80, 250),
    "DFF workshop abstract": (80, 250),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Lint the generated submission packet for missing assets, word counts, and overclaims."
    )
    parser.add_argument("--repo-root", default=".", help="Repository root for validating manifest paths.")
    parser.add_argument(
        "--manifest",
        default="reports/assets/submission_packet_manifest.csv",
        help="Submission packet manifest generated by build_submission_packet.py.",
    )
    parser.add_argument(
        "--text-drafts",
        default="reports/submission_text_drafts_2026_06_14.md",
        help="Generated submission text draft report.",
    )
    parser.add_argument(
        "--word-counts",
        default="reports/assets/submission_text_drafts_word_counts.csv",
        help="Generated abstract word-count table.",
    )
    parser.add_argument(
        "--out-path",
        default="reports/submission_package_lint_2026_06_14.md",
        help="Markdown lint report to write.",
    )
    parser.add_argument(
        "--checks-out",
        default="reports/assets/submission_package_lint.csv",
        help="Machine-readable lint checks to write.",
    )
    return parser.parse_args()


def _word_count(text: str) -> int:
    return len(re.findall(r"\b[\w'-]+\b", text))


def _extract_section(text: str, header: str) -> str:
    pattern = rf"^## {re.escape(header)}\s*$"
    match = re.search(pattern, text, flags=re.MULTILINE)
    if not match:
        return ""
    start = match.end()
    next_match = re.search(r"^## ", text[start:], flags=re.MULTILINE)
    end = start + next_match.start() if next_match else len(text)
    return text[start:end].strip()


def _check_rows() -> list[dict[str, object]]:
    return []


def _add_check(rows: list[dict[str, object]], check: str, passed: bool, detail: str) -> None:
    rows.append({"check": check, "passed": bool(passed), "detail": detail})


def lint_submission_package(
    repo_root: Path,
    manifest_path: Path,
    text_drafts_path: Path,
    word_counts_path: Path,
) -> pd.DataFrame:
    rows = _check_rows()
    repo_root = repo_root.resolve()
    manifest = pd.read_csv(manifest_path)
    text = text_drafts_path.read_text(encoding="utf-8")
    word_counts = pd.read_csv(word_counts_path)

    required_missing = []
    stale_manifest = []
    for artifact in manifest.itertuples(index=False):
        artifact_path = repo_root / artifact.path
        exists = artifact_path.exists()
        required = bool(artifact.required)
        if required and not exists:
            required_missing.append(artifact.path)
        if exists and bool(artifact.exists) != exists:
            stale_manifest.append(artifact.path)
    _add_check(
        rows,
        "required artifacts exist",
        not required_missing,
        "all required artifacts are present" if not required_missing else ", ".join(required_missing),
    )
    _add_check(
        rows,
        "manifest existence flags are current",
        not stale_manifest,
        "manifest existence flags match filesystem" if not stale_manifest else ", ".join(stale_manifest),
    )

    manifest_venues = ",".join(manifest["venues"].dropna().astype(str).tolist())
    for venue in ["DFRWS", "WIFS", "DFF"]:
        _add_check(
            rows,
            f"{venue} artifacts listed",
            venue in manifest_venues,
            f"{venue} appears in packet manifest",
        )

    for header in ABSTRACT_HEADERS:
        section = _extract_section(text, header)
        _add_check(rows, f"{header} section exists", bool(section), "section present" if section else "missing")

    counts_by_name = dict(zip(word_counts["draft"], word_counts["word_count"], strict=True))
    for draft, (minimum, maximum) in WORD_LIMITS.items():
        count = int(counts_by_name.get(draft, -1))
        _add_check(
            rows,
            f"{draft} word count",
            minimum <= count <= maximum,
            f"{count} words; allowed {minimum}-{maximum}",
        )

    for header in ABSTRACT_HEADERS:
        section = _extract_section(text, header)
        if section:
            computed = _word_count(section)
            draft_key = ABSTRACT_TO_DRAFT[header]
            recorded = int(counts_by_name.get(draft_key, -1))
            _add_check(
                rows,
                f"{header} recorded count matches text",
                computed == recorded,
                f"computed {computed}, recorded {recorded}",
            )

    for guardrail in REQUIRED_GUARDRAILS:
        _add_check(
            rows,
            f"guardrail present: {guardrail}",
            guardrail in text,
            "present" if guardrail in text else "missing",
        )

    for finding_id in REQUIRED_RESULT_IDS:
        _add_check(
            rows,
            f"result id present: {finding_id}",
            finding_id in text,
            "present" if finding_id in text else "missing",
        )

    abstract_blob = "\n\n".join(_extract_section(text, header) for header in ABSTRACT_HEADERS)
    for pattern in FORBIDDEN_ABSTRACT_PATTERNS:
        found = re.search(pattern, abstract_blob, flags=re.IGNORECASE) is not None
        _add_check(
            rows,
            f"abstracts avoid overclaim: {pattern}",
            not found,
            "not found" if not found else "found in abstract text",
        )

    return pd.DataFrame(rows)


def _markdown_table(frame: pd.DataFrame) -> str:
    columns = list(frame.columns)
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame.itertuples(index=False):
        lines.append("| " + " | ".join(str(value).replace("\n", " ") for value in row) + " |")
    return "\n".join(lines)


def write_report(frame: pd.DataFrame, out_path: Path) -> None:
    passed = int(frame["passed"].sum())
    total = len(frame)
    status = "PASS" if passed == total else "FAIL"
    lines = [
        "# Submission Package Lint",
        "",
        "Run date: 2026-06-14",
        "",
        f"Status: **{status}** ({passed}/{total} checks passed).",
        "",
        "Generated by `scripts/lint_submission_package.py` from the packet manifest and generated submission text drafts.",
        "",
        _markdown_table(frame),
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    frame = lint_submission_package(
        repo_root=Path(args.repo_root),
        manifest_path=Path(args.manifest),
        text_drafts_path=Path(args.text_drafts),
        word_counts_path=Path(args.word_counts),
    )
    checks_path = Path(args.checks_out)
    checks_path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(checks_path, index=False)
    write_report(frame, Path(args.out_path))
    if not bool(frame["passed"].all()):
        failed = frame[~frame["passed"]]
        raise SystemExit(
            "Submission package lint failed: "
            + "; ".join(f"{row.check} ({row.detail})" for row in failed.itertuples(index=False))
        )
    print(Path(args.out_path).resolve())
    print(checks_path.resolve())


if __name__ == "__main__":
    main()
