from __future__ import annotations

import argparse
import re
from pathlib import Path

import pandas as pd


EXPECTED_DOCUMENT_CLASSES = {
    "wifs_2026": r"\documentclass[conference]{IEEEtran}",
    "dff_2026": r"\documentclass[sigconf,review,anonymous]{acmart}",
}

REQUIRED_COLUMNS = {
    "paper_id",
    "venue",
    "title",
    "path",
    "template_hint",
    "abstract_header",
    "claim_count",
    "citation_count",
    "draft_section_count",
    "todo_count",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Lint generated WIFS/DFF LaTeX skeletons for missing references and claim guardrails."
    )
    parser.add_argument("--repo-root", default=".", help="Repository root for validating relative paths.")
    parser.add_argument(
        "--manifest",
        default="reports/assets/paper_skeletons/submission_paper_skeleton_manifest.csv",
        help="Paper skeleton manifest generated by build_submission_paper_skeletons.py.",
    )
    parser.add_argument(
        "--out-path",
        default="reports/paper_skeleton_lint_2026_06_14.md",
        help="Markdown lint report to write.",
    )
    parser.add_argument(
        "--checks-out",
        default="reports/assets/paper_skeleton_lint.csv",
        help="Machine-readable lint checks to write.",
    )
    return parser.parse_args()


def _add_check(rows: list[dict[str, object]], paper_id: str, check: str, passed: bool, detail: str) -> None:
    rows.append({"paper_id": paper_id, "check": check, "passed": bool(passed), "detail": detail})


def _extract_paths(pattern: str, text: str) -> list[str]:
    return re.findall(pattern, text)


def _paths_exist(repo_root: Path, paths: list[str]) -> tuple[bool, str]:
    missing = [path for path in paths if not (repo_root / path).exists()]
    if missing:
        return False, ", ".join(missing)
    return True, f"{len(paths)} paths present"


def _bib_keys(bib_path: Path) -> set[str]:
    if not bib_path.exists():
        return set()
    text = bib_path.read_text(encoding="utf-8")
    return set(re.findall(r"@\w+\{([^,\s]+)", text))


def _lint_one_skeleton(repo_root: Path, row: pd.Series) -> list[dict[str, object]]:
    checks: list[dict[str, object]] = []
    paper_id = str(row["paper_id"])
    tex_path = repo_root / str(row["path"])
    exists = tex_path.exists()
    _add_check(checks, paper_id, "tex file exists", exists, str(row["path"]) if exists else "missing")
    if not exists:
        return checks

    text = tex_path.read_text(encoding="utf-8")
    expected_class = EXPECTED_DOCUMENT_CLASSES.get(paper_id)
    _add_check(
        checks,
        paper_id,
        "expected documentclass",
        expected_class in text if expected_class else False,
        expected_class or "unknown paper_id",
    )
    for marker in [
        r"\title{",
        r"\begin{document}",
        r"\maketitle",
        r"\begin{abstract}",
        r"\end{abstract}",
        r"\end{document}",
        r"\bibliography{references}",
    ]:
        _add_check(checks, paper_id, f"contains {marker}", marker in text, "present" if marker in text else "missing")

    input_paths = _extract_paths(r"\\input\{([^}]+)\}", text)
    graphics_paths = _extract_paths(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", text)
    inputs_ok, inputs_detail = _paths_exist(repo_root, input_paths)
    figures_ok, figures_detail = _paths_exist(repo_root, graphics_paths)
    _add_check(checks, paper_id, "table input paths exist", inputs_ok and len(input_paths) >= 5, inputs_detail)
    source_stress_table = "reports/assets/latex_tables/source_holdout_stress.tex"
    _add_check(
        checks,
        paper_id,
        "source stress table referenced",
        source_stress_table in input_paths,
        "source stress LaTeX table input present" if source_stress_table in input_paths else "missing",
    )
    _add_check(checks, paper_id, "figure paths exist", figures_ok and len(graphics_paths) >= 5, figures_detail)
    source_stress_path = "reports/assets/source_holdout_generator_stress.png"
    source_stress_present = (
        source_stress_path in graphics_paths
        and r"\label{fig:source-stress}" in text
        and r"\ref{fig:source-stress}" in text
    )
    _add_check(
        checks,
        paper_id,
        "source stress figure referenced",
        source_stress_present,
        "source stress figure path, label, and text reference present" if source_stress_present else "missing",
    )

    references_bib = repo_root / "references.bib"
    references_exist = references_bib.exists()
    _add_check(
        checks,
        paper_id,
        "references.bib exists",
        references_exist,
        "references.bib present" if references_exist else "references.bib missing",
    )
    cite_commands = _extract_paths(r"\\cite\{([^}]+)\}", text)
    cited_keys = [key.strip() for command in cite_commands for key in command.split(",") if key.strip()]
    expected_citations = int(row.get("citation_count", 0))
    _add_check(
        checks,
        paper_id,
        "citation count matches manifest",
        len(cite_commands) == expected_citations,
        f"{len(cite_commands)} cite commands; manifest expects {expected_citations}",
    )
    available_bib_keys = _bib_keys(references_bib)
    missing_bib_keys = sorted(set(cited_keys) - available_bib_keys)
    _add_check(
        checks,
        paper_id,
        "citation keys exist in references.bib",
        not missing_bib_keys and bool(cited_keys),
        f"{len(cited_keys)} cited keys found" if not missing_bib_keys else ", ".join(missing_bib_keys),
    )
    todo_count = len(re.findall(r"\bTODO\b", text))
    expected_todos = int(row.get("todo_count", 0))
    _add_check(
        checks,
        paper_id,
        "no TODO placeholders",
        todo_count == 0 and expected_todos == 0,
        f"{todo_count} TODO markers in tex; manifest records {expected_todos}",
    )
    draft_section_count = int(row.get("draft_section_count", 0))
    _add_check(
        checks,
        paper_id,
        "draft prose sections populated",
        draft_section_count >= 5,
        f"manifest records {draft_section_count} draft prose sections",
    )

    expected_claims = int(row.get("claim_count", 0))
    claim_items = re.findall(r"\\item\s+\\textbf\{", text)
    evidence_count = text.count(r"\textit{Evidence artifact:}")
    caveat_count = text.count(r"\textit{Caveat:}")
    _add_check(
        checks,
        paper_id,
        "claim checklist present",
        "Claim-Evidence Checklist" in text,
        "present" if "Claim-Evidence Checklist" in text else "missing",
    )
    _add_check(
        checks,
        paper_id,
        "claim count matches manifest",
        len(claim_items) == expected_claims,
        f"{len(claim_items)} items; manifest expects {expected_claims}",
    )
    _add_check(
        checks,
        paper_id,
        "claim items include evidence and caveats",
        evidence_count == expected_claims and caveat_count == expected_claims,
        f"{evidence_count} evidence markers, {caveat_count} caveat markers",
    )

    guardrail_terms = [
        ("single-image proxy", ["single-image proxy"]),
        ("does not universally beat CLIP", ["does not universally beat CLIP", "does not universally beat frozen CLIP"]),
        ("robustness transform caveat", ["robustness depends on the transform", "transform being tested"]),
    ]
    for label, alternatives in guardrail_terms:
        found = any(term in text for term in alternatives)
        _add_check(checks, paper_id, f"guardrail term present: {label}", found, "present" if found else "missing")
    return checks


def lint_paper_skeletons(repo_root: Path, manifest_path: Path) -> pd.DataFrame:
    repo_root = repo_root.resolve()
    manifest = pd.read_csv(manifest_path)
    rows: list[dict[str, object]] = []
    missing_columns = REQUIRED_COLUMNS - set(manifest.columns)
    _add_check(
        rows,
        "manifest",
        "required columns present",
        not missing_columns,
        "all required columns present" if not missing_columns else ", ".join(sorted(missing_columns)),
    )
    if missing_columns:
        return pd.DataFrame(rows)

    for row in manifest.to_dict(orient="records"):
        rows.extend(_lint_one_skeleton(repo_root, pd.Series(row)))
    return pd.DataFrame(rows)


def _markdown_table(frame: pd.DataFrame) -> str:
    columns = list(frame.columns)
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame.itertuples(index=False):
        lines.append("| " + " | ".join(str(value).replace("\n", " ") for value in row) + " |")
    return "\n".join(lines)


def write_report(frame: pd.DataFrame, out_path: Path) -> None:
    passed = int(frame["passed"].sum())
    total = len(frame)
    status = "PASS" if passed == total else "FAIL"
    lines = [
        "# Paper Skeleton Lint",
        "",
        "Run date: 2026-06-14",
        "",
        f"Status: **{status}** ({passed}/{total} checks passed).",
        "",
        "Generated by `scripts/lint_paper_skeletons.py` from the WIFS/DFF paper skeleton manifest.",
        "",
        _markdown_table(frame),
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    frame = lint_paper_skeletons(Path(args.repo_root), Path(args.manifest))
    checks_path = Path(args.checks_out)
    checks_path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(checks_path, index=False)
    write_report(frame, Path(args.out_path))
    if not bool(frame["passed"].all()):
        failed = frame[~frame["passed"]]
        raise SystemExit(
            "Paper skeleton lint failed: "
            + "; ".join(f"{row.paper_id}:{row.check} ({row.detail})" for row in failed.itertuples(index=False))
        )
    print(Path(args.out_path).resolve())
    print(checks_path.resolve())


if __name__ == "__main__":
    main()
