from __future__ import annotations

import argparse
import hashlib
from datetime import date
from pathlib import Path

import pandas as pd


DEFAULT_RUN_DATE = date.today()
VALID_STATUSES = {"hashed", "missing", "index_or_self_skipped"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Verify SHA-256 hashes generated for the submission packet artifacts."
    )
    parser.add_argument("--repo-root", default=".", help="Repository root for resolving artifact paths.")
    parser.add_argument(
        "--hashes",
        default="reports/assets/submission_artifact_hashes.csv",
        help="Hash CSV generated by build_submission_artifact_hashes.py.",
    )
    parser.add_argument(
        "--out-path",
        default="reports/submission_artifact_hashes_lint_2026_06_15.md",
        help="Markdown lint report to write.",
    )
    parser.add_argument(
        "--checks-out",
        default="reports/assets/submission_artifact_hashes_lint.csv",
        help="Machine-readable lint checks to write.",
    )
    parser.add_argument(
        "--run-date",
        default=DEFAULT_RUN_DATE.isoformat(),
        help="Date to stamp into the report, in YYYY-MM-DD format. Defaults to today's local date.",
    )
    return parser.parse_args()


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _add_check(rows: list[dict[str, object]], check: str, passed: bool, detail: str) -> None:
    rows.append({"check": check, "passed": bool(passed), "detail": detail})


def _markdown_table(frame: pd.DataFrame) -> str:
    columns = list(frame.columns)
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame.itertuples(index=False):
        lines.append("| " + " | ".join(str(value).replace("\n", " ") for value in row) + " |")
    return "\n".join(lines)


def lint_artifact_hashes(repo_root: Path, hashes_path: Path) -> pd.DataFrame:
    repo_root = repo_root.resolve()
    hashes_path = hashes_path if hashes_path.is_absolute() else repo_root / hashes_path
    hashes = pd.read_csv(hashes_path)
    rows: list[dict[str, object]] = []

    required_columns = {"path", "exists", "size_bytes", "sha256", "hash_status"}
    missing_columns = sorted(required_columns - set(hashes.columns))
    _add_check(
        rows,
        "required columns present",
        not missing_columns,
        "all required columns present" if not missing_columns else f"missing columns: {missing_columns}",
    )
    if missing_columns:
        return pd.DataFrame(rows)

    statuses = set(hashes["hash_status"].dropna().astype(str))
    invalid_statuses = sorted(statuses - VALID_STATUSES)
    _add_check(
        rows,
        "hash statuses valid",
        not invalid_statuses,
        "all statuses valid" if not invalid_statuses else f"invalid statuses: {invalid_statuses}",
    )

    hash_mismatches = []
    missing_hashed = []
    size_mismatches = []
    skipped_count = 0
    skipped_missing = []
    missing_rows_present = []
    for row in hashes.itertuples(index=False):
        path = repo_root / str(row.path)
        exists = path.exists()
        status = str(row.hash_status)
        if status == "hashed":
            if not exists:
                missing_hashed.append(row.path)
                continue
            actual_hash = _sha256_file(path)
            if actual_hash != str(row.sha256):
                hash_mismatches.append(row.path)
            expected_size = None if pd.isna(row.size_bytes) else int(row.size_bytes)
            actual_size = path.stat().st_size
            if expected_size is not None and actual_size != expected_size:
                size_mismatches.append(row.path)
        elif status == "index_or_self_skipped":
            skipped_count += 1
            if not exists:
                skipped_missing.append(row.path)
        elif status == "missing" and exists:
            missing_rows_present.append(row.path)

    _add_check(
        rows,
        "hashed artifacts exist",
        not missing_hashed,
        "all hashed artifacts exist" if not missing_hashed else f"missing hashed artifacts: {missing_hashed[:10]}",
    )
    _add_check(
        rows,
        "sha256 values match",
        not hash_mismatches,
        "all checked hashes match" if not hash_mismatches else f"hash mismatches: {hash_mismatches[:10]}",
    )
    _add_check(
        rows,
        "size values match",
        not size_mismatches,
        "all checked sizes match" if not size_mismatches else f"size mismatches: {size_mismatches[:10]}",
    )
    _add_check(
        rows,
        "skipped index files ignored",
        True,
        f"{skipped_count} index/self files skipped; missing skipped files: {skipped_missing[:10]}"
        if skipped_missing
        else f"{skipped_count} index/self files skipped",
    )
    _add_check(
        rows,
        "missing artifacts still absent",
        not missing_rows_present,
        "all missing-status artifacts are absent"
        if not missing_rows_present
        else f"missing-status artifacts now present: {missing_rows_present[:10]}",
    )
    return pd.DataFrame(rows)


def write_report(frame: pd.DataFrame, out_path: Path, run_date: date) -> None:
    passed = int(frame["passed"].sum())
    total = len(frame)
    status = "PASS" if passed == total else "FAIL"
    lines = [
        "# Submission Artifact Hash Lint",
        "",
        f"Run date: {run_date.isoformat()}",
        "",
        f"Status: **{status}** ({passed}/{total} checks passed).",
        "",
        "Generated by `scripts/lint_submission_artifact_hashes.py` from `reports/assets/submission_artifact_hashes.csv`.",
        "",
        _markdown_table(frame),
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    args = parse_args()
    run_date = date.fromisoformat(args.run_date)
    repo_root = Path(args.repo_root).resolve()
    frame = lint_artifact_hashes(repo_root=repo_root, hashes_path=Path(args.hashes))
    checks_out = Path(args.checks_out)
    checks_out = checks_out if checks_out.is_absolute() else repo_root / checks_out
    checks_out.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(checks_out, index=False)
    out_path = Path(args.out_path)
    out_path = out_path if out_path.is_absolute() else repo_root / out_path
    write_report(frame, out_path, run_date)
    if not bool(frame["passed"].all()):
        failed = frame[~frame["passed"]]
        raise SystemExit(
            "Submission artifact hash lint failed: "
            + "; ".join(f"{row.check} ({row.detail})" for row in failed.itertuples(index=False))
        )
    print(out_path.resolve())
    print(checks_out.resolve())


if __name__ == "__main__":
    main()
