from __future__ import annotations

import argparse
import hashlib
import zipfile
from datetime import date
from pathlib import Path, PurePosixPath

import pandas as pd


DEFAULT_RUN_DATE = date.today()
SAFE_STATUSES = {"safe", "not_scanned_binary"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create and validate a deterministic zip for the anonymous review artifact bundle."
    )
    parser.add_argument("--repo-root", default=".", help="Repository root for resolving bundle paths.")
    parser.add_argument(
        "--bundle-manifest",
        default="reports/assets/anonymous_review_bundle_manifest.csv",
        help="Manifest generated by build_anonymous_review_bundle.py.",
    )
    parser.add_argument(
        "--zip-out",
        default="outputs/anonymous_review_bundle_2026_06_15.zip",
        help="Local zip archive to write. The default outputs/ path is intentionally ignored by git.",
    )
    parser.add_argument(
        "--out-path",
        default="reports/anonymous_review_bundle_package_2026_06_15.md",
        help="Markdown package report to write.",
    )
    parser.add_argument(
        "--entries-out",
        default="reports/assets/anonymous_review_bundle_zip_manifest.csv",
        help="Machine-readable zip entry manifest to write.",
    )
    parser.add_argument(
        "--archive-prefix",
        default="anonymous_review_bundle",
        help="Top-level folder name to use inside the zip archive.",
    )
    parser.add_argument(
        "--run-date",
        default=DEFAULT_RUN_DATE.isoformat(),
        help="Date to stamp into the report and deterministic zip entries, in YYYY-MM-DD format.",
    )
    return parser.parse_args()


def _repo_path(repo_root: Path, path: Path) -> Path:
    return path if path.is_absolute() else repo_root / path


def _repo_relative(repo_root: Path, path: Path) -> str:
    try:
        return path.resolve().relative_to(repo_root).as_posix()
    except ValueError:
        return path.as_posix()


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _markdown_escape(value: object) -> str:
    if value is None or pd.isna(value):
        return ""
    return str(value).replace("\n", " ").replace("|", "\\|")


def _markdown_table(frame: pd.DataFrame, columns: list[str]) -> str:
    lines = [
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]
    for row in frame[columns].itertuples(index=False):
        lines.append("| " + " | ".join(_markdown_escape(value) for value in row) + " |")
    return "\n".join(lines)


def _archive_path(prefix: str, relative_path: str) -> str:
    relative = PurePosixPath(relative_path.replace("\\", "/"))
    if relative.is_absolute() or ".." in relative.parts:
        raise ValueError(f"Unsafe bundle path for zip archive: {relative_path}")
    normalized_prefix = PurePosixPath(prefix.strip("/"))
    if not str(normalized_prefix) or normalized_prefix.is_absolute() or ".." in normalized_prefix.parts:
        raise ValueError(f"Unsafe archive prefix: {prefix}")
    return str(normalized_prefix / relative)


def package_anonymous_review_bundle(
    repo_root: Path,
    bundle_manifest: Path,
    zip_out: Path,
    out_path: Path,
    entries_out: Path,
    archive_prefix: str = "anonymous_review_bundle",
    run_date: date = DEFAULT_RUN_DATE,
) -> tuple[str, pd.DataFrame]:
    repo_root = repo_root.resolve()
    bundle_manifest = _repo_path(repo_root, bundle_manifest)
    zip_out = _repo_path(repo_root, zip_out)
    out_path = _repo_path(repo_root, out_path)
    entries_out = _repo_path(repo_root, entries_out)
    manifest = pd.read_csv(bundle_manifest)

    rows = []
    for row in manifest.sort_values("path").itertuples(index=False):
        relative_path = str(row.path).replace("\\", "/")
        full_path = repo_root / relative_path
        exists = bool(full_path.exists())
        anonymous_status = str(row.anonymous_status)
        include_ok = exists and anonymous_status in SAFE_STATUSES
        source_sha256 = _sha256_file(full_path) if exists else pd.NA
        expected_sha256 = str(row.sha256) if not pd.isna(row.sha256) else ""
        source_hash_matches_manifest = bool(exists and expected_sha256 and source_sha256 == expected_sha256)
        rows.append(
            {
                "path": relative_path,
                "archive_path": _archive_path(archive_prefix, relative_path),
                "section": row.section,
                "venues": row.venues,
                "required": bool(row.required),
                "exists": exists,
                "anonymous_status": anonymous_status,
                "source_size_bytes": int(full_path.stat().st_size) if exists else pd.NA,
                "source_sha256": source_sha256,
                "source_hash_matches_manifest": source_hash_matches_manifest,
                "include_status": "included" if include_ok else "blocked",
            }
        )
    entries = pd.DataFrame(rows)
    blocked = entries[entries["include_status"] != "included"]

    if blocked.empty:
        zip_out.parent.mkdir(parents=True, exist_ok=True)
        zip_timestamp = (run_date.year, run_date.month, run_date.day, 0, 0, 0)
        with zipfile.ZipFile(zip_out, mode="w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
            for entry in entries.itertuples(index=False):
                zip_info = zipfile.ZipInfo(str(entry.archive_path), date_time=zip_timestamp)
                zip_info.compress_type = zipfile.ZIP_DEFLATED
                zip_info.external_attr = 0o644 << 16
                archive.writestr(zip_info, (repo_root / str(entry.path)).read_bytes())
        with zipfile.ZipFile(zip_out, mode="r") as archive:
            by_name = {info.filename: info for info in archive.infolist()}
        entries["zip_compressed_size"] = entries["archive_path"].map(lambda name: by_name[name].compress_size)
        entries["zip_crc"] = entries["archive_path"].map(lambda name: f"{by_name[name].CRC:08x}")
        zip_sha256 = _sha256_file(zip_out)
        zip_size = int(zip_out.stat().st_size)
    else:
        entries["zip_compressed_size"] = pd.NA
        entries["zip_crc"] = pd.NA
        zip_sha256 = ""
        zip_size = 0

    duplicate_archive_paths = entries[entries["archive_path"].duplicated(keep=False)]
    unsafe_archive_paths = entries[
        entries["archive_path"].str.startswith("/")
        | entries["archive_path"].str.contains(r"(?:^|/)\.\.(?:/|$)", regex=True)
        | entries["archive_path"].str.contains("\\", regex=False)
    ]
    check_rows = [
        {
            "check": "bundle manifest exists",
            "passed": bool(bundle_manifest.exists()),
            "detail": _repo_relative(repo_root, bundle_manifest),
        },
        {
            "check": "all entries included",
            "passed": blocked.empty,
            "detail": f"{len(blocked)} blocked entrie(s)",
        },
        {
            "check": "source hashes match bundle manifest",
            "passed": bool(entries["source_hash_matches_manifest"].all()) if not entries.empty else True,
            "detail": f"{int(entries['source_hash_matches_manifest'].sum())}/{len(entries)} source hash(es) matched",
        },
        {
            "check": "archive paths are safe",
            "passed": duplicate_archive_paths.empty and unsafe_archive_paths.empty,
            "detail": f"{len(duplicate_archive_paths)} duplicate and {len(unsafe_archive_paths)} unsafe archive path row(s)",
        },
        {
            "check": "zip archive created",
            "passed": bool(blocked.empty and zip_out.exists() and zip_size > 0),
            "detail": _repo_relative(repo_root, zip_out),
        },
    ]
    checks = pd.DataFrame(check_rows)
    passed = int(checks["passed"].sum())
    total = int(len(checks))
    status = "PASS" if passed == total else "FAIL"

    entries_out.parent.mkdir(parents=True, exist_ok=True)
    entries.to_csv(entries_out, index=False)
    lines = [
        "# Anonymous Review Bundle Package",
        "",
        f"Run date: {run_date.isoformat()}",
        "",
        f"Status: **{status}** ({passed}/{total} checks passed).",
        "",
        "Generated by `scripts/package_anonymous_review_bundle.py` from `reports/assets/anonymous_review_bundle_manifest.csv`.",
        "",
        "The zip is built locally under `outputs/` so the archive does not bloat the git repository. This report and CSV record the archive entries, source hashes, CRCs, and final zip SHA-256.",
        "",
        "## Zip",
        "",
        f"- Path: `{_repo_relative(repo_root, zip_out)}`",
        f"- Size bytes: `{zip_size}`",
        f"- SHA-256: `{zip_sha256}`" if zip_sha256 else "- SHA-256: `not-created`",
        f"- Entries: `{len(entries)}`",
        "",
        "## Checks",
        "",
        _markdown_table(checks, ["check", "passed", "detail"]),
        "",
        "## Blocked Entries",
        "",
        "None." if blocked.empty else _markdown_table(blocked, ["path", "anonymous_status", "include_status"]),
        "",
        "## Entries",
        "",
        _markdown_table(
            entries,
            [
                "archive_path",
                "path",
                "section",
                "anonymous_status",
                "source_sha256",
                "zip_crc",
            ],
        ),
        "",
        f"Machine-readable zip manifest: `{_repo_relative(repo_root, entries_out)}`",
        "",
    ]
    text = "\n".join(lines)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    return text, entries


def main() -> None:
    args = parse_args()
    text, entries = package_anonymous_review_bundle(
        repo_root=Path(args.repo_root),
        bundle_manifest=Path(args.bundle_manifest),
        zip_out=Path(args.zip_out),
        out_path=Path(args.out_path),
        entries_out=Path(args.entries_out),
        archive_prefix=args.archive_prefix,
        run_date=date.fromisoformat(args.run_date),
    )
    print(Path(args.out_path).resolve())
    print(Path(args.entries_out).resolve())
    print(Path(args.zip_out).resolve())
    if not text:
        raise SystemExit("No anonymous review bundle package report generated")
    if not entries["include_status"].eq("included").all():
        raise SystemExit("Anonymous review bundle package has blocked entries")


if __name__ == "__main__":
    main()
